# Import library

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from collections import Counter
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from jcopml.utils import save_model
from jcopml.utils import load_model

# Data preprocessing

In [2]:
# read data
df = pd.read_csv('Dataset_Discoaster(Self-Rev).csv')
df.head()

,Jumlah_Lengan,Bercabang,Knob,Bentuk_Lengan,Ujung_Lengan,Spesies
0,17,Tidak,Ya,Tebal,Tumpul,Discoasteroides bramlettei
1,18,Tidak,Ya,Tebal,Tumpul,Discoasteroides bramlettei
2,19,Tidak,Ya,Tebal,Tumpul,Discoasteroides bramlettei
3,20,Tidak,Ya,Tebal,Tumpul,Discoasteroides bramlettei
4,21,Tidak,Ya,Tebal,Tumpul,Discoasteroides bramlettei

In [3]:
df.shape

(435, 6)

In [4]:
# feautures encoding
ordl_encoder = preprocessing.OrdinalEncoder(dtype=int)
ordl_encoder.fit(df[['Bercabang', 'Knob', 'Bentuk_Lengan', 'Ujung_Lengan']])
df[['Bercabang', 'Knob', 'Bentuk_Lengan', 'Ujung_Lengan']] = ordl_encoder.transform(df[['Bercabang', 'Knob', 'Bentuk_Lengan', 'Ujung_Lengan']])

In [5]:
df.head()

,Jumlah_Lengan,Bercabang,Knob,Bentuk_Lengan,Ujung_Lengan,Spesies
0,17,0,1,1,1,Discoasteroides bramlettei
1,18,0,1,1,1,Discoasteroides bramlettei
2,19,0,1,1,1,Discoasteroides bramlettei
3,20,0,1,1,1,Discoasteroides bramlettei
4,21,0,1,1,1,Discoasteroides bramlettei

In [6]:
# target label encoding
lbl_encoder = preprocessing.LabelEncoder()
lbl_encoder.fit(df['Spesies'])
df['Spesies'] = lbl_encoder.transform(df['Spesies'])

In [7]:
df.head()

   Jumlah_Lengan  Bercabang  Knob  Bentuk_Lengan  Ujung_Lengan  Spesies
0             17          0     1              1             1      136
1             18          0     1              1             1      136
2             19          0     1              1             1      136
3             20          0     1              1             1      136
4             21          0     1              1             1      136

In [8]:
df.shape

(435, 6)

In [9]:
# check dataset balance
sorted(df['Spesies'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136]

In [10]:
print(sorted(Counter(df['Spesies']).items()))

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 6), (6, 1), (7, 3), (8, 1), (9, 2), (10, 2), (11, 1), (12, 3), (13, 3), (14, 8), (15, 1), (16, 1), (17, 1), (18, 4), (19, 6), (20, 6), (21, 1), (22, 2), (23, 3), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 6), (31, 1), (32, 3), (33, 2), (34, 2), (35, 2), (36, 3), (37, 21), (38, 1), (39, 8), (40, 2), (41, 4), (42, 5), (43, 2), (44, 16), (45, 4), (46, 2), (47, 3), (48, 5), (49, 3), (50, 1), (51, 1), (52, 1), (53, 1), (54, 1), (55, 1), (56, 1), (57, 1), (58, 5), (59, 1), (60, 1), (61, 7), (62, 4), (63, 3), (64, 4), (65, 1), (66, 6), (67, 1), (68, 4), (69, 1), (70, 20), (71, 3), (72, 1), (73, 1), (74, 3), (75, 1), (76, 1), (77, 8), (78, 1), (79, 2), (80, 40), (81, 1), (82, 1), (83, 1), (84, 1), (85, 7), (86, 4), (87, 1), (88, 1), (89, 4), (90, 12), (91, 3), (92, 1), (93, 1), (94, 1), (95, 5), (96, 9), (97, 1), (98, 3), (99, 1), (100, 1), (101, 2), (102, 1), (103, 1), (104, 1), (105, 1), (106, 2), (107, 1), (108, 1), (109, 8), (110, 13), (111, 1), (112, 2), (113, 1), (114, 1), (115, 4), (116, 5), (117, 1), (118, 1), (119, 4), (120, 1), (121, 1), (122, 1), (123, 2), (124, 1), (125, 1), (126, 2), (127, 2), (128, 1), (129, 1), (130, 4), (131, 1), (132, 11), (133, 1), (134, 1), (135, 1), (136, 5)]

In [11]:
df['Spesies'].value_counts().describe()

count    137.000000
mean       3.175182
std        4.652478
min        1.000000
25%        1.000000
50%        1.000000
75%        4.000000
max       40.000000
Name: Spesies, dtype: float64

In [12]:
# features and targets split
X = df[['Jumlah_Lengan', 'Bercabang', 'Knob', 'Bentuk_Lengan', 'Ujung_Lengan']]
X

     Jumlah_Lengan  Bercabang  Knob  Bentuk_Lengan  Ujung_Lengan
0               17          0     1              1             1
1               18          0     1              1             1
2               19          0     1              1             1
3               20          0     1              1             1
4               21          0     1              1             1
..             ...        ...   ...            ...           ...
430              5          1     0              1             1
431              6          1     0              1             1
432             10          0     1              1             1
433             11          0     1              1             1
434              6          1     1              1             1

[435 rows x 5 columns]

In [13]:
y = df['Spesies']
y

0      136
1      136
2      136
3      136
4      136
      ...
430     63
431     63
432     10
433     10
434     55
Name: Spesies, Length: 435, dtype: int32

In [14]:
# random oversampling
ros = RandomOverSampler(random_state=0)
X_resampled, y_resampled = ros.fit_resample(X, y)

In [15]:
# repeat check dataset balance
X_resampled

      Jumlah_Lengan  Bercabang  Knob  Bentuk_Lengan  Ujung_Lengan
0                17          0     1              1             1
1                18          0     1              1             1
2                19          0     1              1             1
3                20          0     1              1             1
4                21          0     1              1             1
...             ...        ...   ...            ...           ...
5475             19          0     1              1             1
5476             17          0     1              1             1
5477             20          0     1              1             1
5478             20          0     1              1             1
5479             17          0     1              1             1

[5480 rows x 5 columns]

In [16]:
y_resampled

0       136
1       136
2       136
3       136
4       136
       ...
5475    136
5476    136
5477    136
5478    136
5479    136
Name: Spesies, Length: 5480, dtype: int32

In [17]:
print(sorted(Counter(y_resampled).items()))

[(0, 40), (1, 40), (2, 40), (3, 40), (4, 40), (5, 40), (6, 40), (7, 40), (8, 40), (9, 40), (10, 40), (11, 40), (12, 40), (13, 40), (14, 40), (15, 40), (16, 40), (17, 40), (18, 40), (19, 40), (20, 40), (21, 40), (22, 40), (23, 40), (24, 40), (25, 40), (26, 40), (27, 40), (28, 40), (29, 40), (30, 40), (31, 40), (32, 40), (33, 40), (34, 40), (35, 40), (36, 40), (37, 40), (38, 40), (39, 40), (40, 40), (41, 40), (42, 40), (43, 40), (44, 40), (45, 40), (46, 40), (47, 40), (48, 40), (49, 40), (50, 40), (51, 40), (52, 40), (53, 40), (54, 40), (55, 40), (56, 40), (57, 40), (58, 40), (59, 40), (60, 40), (61, 40), (62, 40), (63, 40), (64, 40), (65, 40), (66, 40), (67, 40), (68, 40), (69, 40), (70, 40), (71, 40), (72, 40), (73, 40), (74, 40), (75, 40), (76, 40), (77, 40), (78, 40), (79, 40), (80, 40), (81, 40), (82, 40), (83, 40), (84, 40), (85, 40), (86, 40), (87, 40), (88, 40), (89, 40), (90, 40), (91, 40), (92, 40), (93, 40), (94, 40), (95, 40), (96, 40), (97, 40), (98, 40), (99, 40), (100, 40), (101, 40), (102, 40), (103, 40), (104, 40), (105, 40), (106, 40), (107, 40), (108, 40), (109, 40), (110, 40), (111, 40), (112, 40), (113, 40), (114, 40), (115, 40), (116, 40), (117, 40), (118, 40), (119, 40), (120, 40), (121, 40), (122, 40), (123, 40), (124, 40), (125, 40), (126, 40), (127, 40), (128, 40), (129, 40), (130, 40), (131, 40), (132, 40), (133, 40), (134, 40), (135, 40), (136, 40)]

In [18]:
y_resampled.value_counts().describe()

count    137.0
mean      40.0
std        0.0
min       40.0
25%       40.0
50%       40.0
75%       40.0
max       40.0
Name: Spesies, dtype: float64

Train Test Split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=1945, stratify=y_resampled)

In [20]:
print(sorted(Counter(y_train).items()))

[(0, 32), (1, 32), (2, 32), (3, 32), (4, 32), (5, 32), (6, 32), (7, 32), (8, 32), (9, 32), (10, 32), (11, 32), (12, 32), (13, 32), (14, 32), (15, 32), (16, 32), (17, 32), (18, 32), (19, 32), (20, 32), (21, 32), (22, 32), (23, 32), (24, 32), (25, 32), (26, 32), (27, 32), (28, 32), (29, 32), (30, 32), (31, 32), (32, 32), (33, 32), (34, 32), (35, 32), (36, 32), (37, 32), (38, 32), (39, 32), (40, 32), (41, 32), (42, 32), (43, 32), (44, 32), (45, 32), (46, 32), (47, 32), (48, 32), (49, 32), (50, 32), (51, 32), (52, 32), (53, 32), (54, 32), (55, 32), (56, 32), (57, 32), (58, 32), (59, 32), (60, 32), (61, 32), (62, 32), (63, 32), (64, 32), (65, 32), (66, 32), (67, 32), (68, 32), (69, 32), (70, 32), (71, 32), (72, 32), (73, 32), (74, 32), (75, 32), (76, 32), (77, 32), (78, 32), (79, 32), (80, 32), (81, 32), (82, 32), (83, 32), (84, 32), (85, 32), (86, 32), (87, 32), (88, 32), (89, 32), (90, 32), (91, 32), (92, 32), (93, 32), (94, 32), (95, 32), (96, 32), (97, 32), (98, 32), (99, 32), (100, 32), (101, 32), (102, 32), (103, 32), (104, 32), (105, 32), (106, 32), (107, 32), (108, 32), (109, 32), (110, 32), (111, 32), (112, 32), (113, 32), (114, 32), (115, 32), (116, 32), (117, 32), (118, 32), (119, 32), (120, 32), (121, 32), (122, 32), (123, 32), (124, 32), (125, 32), (126, 32), (127, 32), (128, 32), (129, 32), (130, 32), (131, 32), (132, 32), (133, 32), (134, 32), (135, 32), (136, 32)]

In [21]:
y_train.value_counts().describe()

count    137.0
mean      32.0
std        0.0
min       32.0
25%       32.0
50%       32.0
75%       32.0
max       32.0
Name: Spesies, dtype: float64

In [22]:
print(sorted(Counter(y_test).items()))

[(0, 8), (1, 8), (2, 8), (3, 8), (4, 8), (5, 8), (6, 8), (7, 8), (8, 8), (9, 8), (10, 8), (11, 8), (12, 8), (13, 8), (14, 8), (15, 8), (16, 8), (17, 8), (18, 8), (19, 8), (20, 8), (21, 8), (22, 8), (23, 8), (24, 8), (25, 8), (26, 8), (27, 8), (28, 8), (29, 8), (30, 8), (31, 8), (32, 8), (33, 8), (34, 8), (35, 8), (36, 8), (37, 8), (38, 8), (39, 8), (40, 8), (41, 8), (42, 8), (43, 8), (44, 8), (45, 8), (46, 8), (47, 8), (48, 8), (49, 8), (50, 8), (51, 8), (52, 8), (53, 8), (54, 8), (55, 8), (56, 8), (57, 8), (58, 8), (59, 8), (60, 8), (61, 8), (62, 8), (63, 8), (64, 8), (65, 8), (66, 8), (67, 8), (68, 8), (69, 8), (70, 8), (71, 8), (72, 8), (73, 8), (74, 8), (75, 8), (76, 8), (77, 8), (78, 8), (79, 8), (80, 8), (81, 8), (82, 8), (83, 8), (84, 8), (85, 8), (86, 8), (87, 8), (88, 8), (89, 8), (90, 8), (91, 8), (92, 8), (93, 8), (94, 8), (95, 8), (96, 8), (97, 8), (98, 8), (99, 8), (100, 8), (101, 8), (102, 8), (103, 8), (104, 8), (105, 8), (106, 8), (107, 8), (108, 8), (109, 8), (110, 8), (111, 8), (112, 8), (113, 8), (114, 8), (115, 8), (116, 8), (117, 8), (118, 8), (119, 8), (120, 8), (121, 8), (122, 8), (123, 8), (124, 8), (125, 8), (126, 8), (127, 8), (128, 8), (129, 8), (130, 8), (131, 8), (132, 8), (133, 8), (134, 8), (135, 8), (136, 8)]

In [23]:
y_test.value_counts().describe()

count    137.0
mean       8.0
std        0.0
min        8.0
25%        8.0
50%        8.0
75%        8.0
max        8.0
Name: Spesies, dtype: float64

# Algorithm Selection Test

In [24]:
# Support Vector Machine
svm = SVC()
svm_cv_results = cross_val_score(svm, X_train, y_train, cv=5, verbose=3)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] END ................................ score: (test=0.235) total time=   3.0s

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.0s remaining:    0.0s

[CV] END ................................ score: (test=0.230) total time=   1.6s

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    4.6s remaining:    0.0s

[CV] END ................................ score: (test=0.283) total time=   1.6s
[CV] END ................................ score: (test=0.223) total time=   1.5s
[CV] END ................................ score: (test=0.251) total time=   1.5s

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    9.6s finished

In [25]:
print("accuracy: {}, std: {}".format(svm_cv_results.mean(), svm_cv_results.std()))

accuracy: 0.2445270562263424, std: 0.02118574577806894

In [26]:
# Random Forest
random_forest = RandomForestClassifier()
random_forest_cv_results = cross_val_score(random_forest, X_train, y_train, cv=5, verbose=3)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] END ................................ score: (test=0.373) total time=   0.2s

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s

[CV] END ................................ score: (test=0.367) total time=   0.2s

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.5s remaining:    0.0s

[CV] END ................................ score: (test=0.363) total time=   0.2s
[CV] END ................................ score: (test=0.368) total time=   0.2s
[CV] END ................................ score: (test=0.365) total time=   0.2s

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    1.4s finished

In [27]:
print("accuracy: {}, std: {}".format(random_forest_cv_results.mean(), random_forest_cv_results.std()))

accuracy: 0.3672440813691341, std: 0.0034072544857375927

In [28]:
# neural network
neural_network = MLPClassifier()
neural_network_cv_results = cross_val_score(neural_network, X_train, y_train, cv=5, verbose=3)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
D:\ProgramFiles\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    9.4s remaining:    0.0s

[CV] END ................................ score: (test=0.338) total time=   9.4s

D:\ProgramFiles\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   18.7s remaining:    0.0s

[CV] END ................................ score: (test=0.314) total time=   9.2s

D:\ProgramFiles\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV] END ................................ score: (test=0.332) total time=   9.2s

D:\ProgramFiles\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV] END ................................ score: (test=0.341) total time=   9.2s
[CV] END ................................ score: (test=0.331) total time=   9.1s

D:\ProgramFiles\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   46.5s finished

In [29]:
print("accuracy: {}, std: {}".format(neural_network_cv_results.mean(), neural_network_cv_results.std()))

accuracy: 0.3309762942367869, std: 0.00944077105094315

In [30]:
# print each model accuracy (std)
print("svm(svc): {} ({})".format(svm_cv_results.mean(), svm_cv_results.std()))
print("random forest: {} ({})".format(random_forest_cv_results.mean(), random_forest_cv_results.std()))
print("neural network: {} ({})".format(neural_network_cv_results.mean(), neural_network_cv_results.std()))

svm(svc): 0.2445270562263424 (0.02118574577806894)
random forest: 0.3672440813691341 (0.0034072544857375927)
neural network: 0.3309762942367869 (0.00944077105094315)

# Create Model

In [31]:
# number of trees in random forest
n_estimators = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
# split criterion
criterion = ["gini", "entropy"]
# maximum number of levels in tree
max_depth = [5, 10, 15, 20, 25, 30, None]
# max considered features per split
max_features = ["auto", "log2", None]
# min samples per leaf node
min_samples_leaf = [1, 2, 3, 4, 5]
# create the params grid
param_grid = {'n_estimators': n_estimators,
              'criterion': criterion,
               'max_depth': max_depth,
             'max_features': max_features,
             'min_samples_leaf': min_samples_leaf}

In [49]:
# GridSearchCV fit
model = RandomForestClassifier(n_jobs=2, random_state=1)

grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring="accuracy", cv=5, verbose=3)
grid_result = grid.fit(X_train, y_train)

Fitting 5 folds for each of 2100 candidates, totalling 10500 fits
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s

[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.6s

[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s

[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.4s

[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   0.8s

[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s

[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.7s

[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s

[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.5s

[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   0.8s

[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s

[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s

[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s

[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s

[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s

[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s

[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.3s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s

[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s

[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.6s

[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s

[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s

[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s

[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s

[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.5s

[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.9s

[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s

[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s

[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.0s

[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s

[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s

[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s

[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s

[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s

[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.2s

[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s

[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s

[CV 2/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s

[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s

[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s

[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.6s

[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.1s

[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s

[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s

[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s

[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s

[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s

[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s

[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s

[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s

[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s

[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s

[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s

[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s

[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s

[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s

[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s

[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.9s

[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s

[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s

[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s

[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s

[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s

[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s

[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s

[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.0s

[CV 4/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=gini, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s

[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s

[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s

[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s

[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s

[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s

[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s

[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s

[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s

[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s

[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.0s

[CV 3/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=gini, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.2s

[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.5s

[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s

[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s

[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.7s

[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s

[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s

[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   0.8s

[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s

[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.5s

[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   0.9s

[CV 1/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s

[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s

[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s

[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s

[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s

[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s

[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s

[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s

[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s

[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s

[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s

[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s

[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s

[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s

[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s

[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s

[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s

[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.4s

[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.1s

[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s

[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s

[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s

[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s

[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s

[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   0.9s

[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s

[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s

[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s

[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s

[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   0.8s

[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s

[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s

[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s

[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s

[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   2.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.8s

[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.2s

[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s

[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.1s

[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   2.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   2.0s

[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   2.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   2.0s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   2.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.5s

[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   2.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   2.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   2.0s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   2.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.3s

[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   2.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s

[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   2.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   2.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   2.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   2.2s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   2.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   2.4s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   2.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.7s

[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   2.0s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   2.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   2.0s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.6s

[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=25, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   2.0s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s

[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   2.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.9s

[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.8s

[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.9s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   2.0s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s

[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.0s

[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.8s

[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   2.0s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.5s

[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.9s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.4s

[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   2.0s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   2.0s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   2.0s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   2.0s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   2.1s

[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   2.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   2.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   2.0s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   2.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   2.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.7s

[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   2.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.4s

[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.9s
[CV 4/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=30, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=350; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=400; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   2.0s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   2.0s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   2.0s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s

[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=350; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=450; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   2.0s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   2.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=2, n_estimators=500; total time=   2.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.6s

[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=400; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=3, n_estimators=500; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=350; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.4s

[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=450; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=4, n_estimators=500; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=400; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=auto, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s

[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=450; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   2.0s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=1, n_estimators=500; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=200; total time=   0.6s

[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=250; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=350; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=400; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=2, n_estimators=500; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=150; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.4s

[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=400; total time=   1.4s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=450; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=3, n_estimators=500; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=150; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=250; total time=   0.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=350; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=400; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=450; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=4, n_estimators=500; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=50; total time=   0.1s

[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=100; total time=   0.2s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=150; total time=   0.4s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=200; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=250; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=350; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=400; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=450; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   2.2s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=log2, min_samples_leaf=5, n_estimators=500; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=200; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.9s

[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=250; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=350; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=450; total time=   1.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=1, n_estimators=500; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.2s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=300; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=350; total time=   1.2s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.4s

[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=400; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=450; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=2, n_estimators=500; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=250; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=300; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.2s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   1.0s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.9s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=350; total time=   0.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=400; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   2.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=450; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=3, n_estimators=500; total time=   1.8s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.3s

[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=150; total time=   0.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   0.9s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   1.2s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=250; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=300; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.4s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=350; total time=   1.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.5s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.5s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=400; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   2.0s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.9s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=450; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   2.0s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   2.0s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   2.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   2.0s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=4, n_estimators=500; total time=   2.0s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.2s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=50; total time=   0.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=100; total time=   0.3s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.6s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=150; total time=   0.6s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.8s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=200; total time=   0.7s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   1.0s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   0.9s

[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   1.0s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=250; total time=   1.0s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.4s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.4s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.3s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.2s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=300; total time=   1.1s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.4s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.5s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=350; total time=   1.5s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.5s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.6s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.7s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.6s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=400; total time=   1.6s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   2.0s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.7s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.8s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.9s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=450; total time=   1.9s
[CV 1/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   1.9s
[CV 2/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   2.1s
[CV 3/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   2.2s
[CV 4/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   2.1s
[CV 5/5] END criterion=entropy, max_depth=None, max_features=None, min_samples_leaf=5, n_estimators=500; total time=   2.1s

In [50]:
# GridSearchCV result
print("Best: {} using {}".format(round(grid_result.best_score_, 6), grid_result.best_params_)) 

means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']

for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.368157 using {'criterion': 'entropy', 'max_depth': 10, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 300}
0.333714 (0.005466) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 50}
0.335540 (0.004586) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 100}
0.339189 (0.005703) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 150}
0.341242 (0.004230) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 200}
0.337821 (0.008557) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 250}
0.341014 (0.007180) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 300}
0.342382 (0.004966) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 350}
0.342610 (0.004155) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 400}
0.344891 (0.004849) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 450}
0.345347 (0.004496) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 500}
0.332346 (0.004398) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 50}
0.335768 (0.005026) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 100}
0.339645 (0.005794) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 150}
0.339645 (0.004498) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 200}
0.337365 (0.009092) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 250}
0.341471 (0.006788) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 300}
0.342610 (0.004648) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 350}
0.342610 (0.004155) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 400}
0.345347 (0.005092) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 450}
0.345575 (0.004640) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 500}
0.331205 (0.002264) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 50}
0.331891 (0.006360) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 100}
0.337820 (0.006023) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 150}
0.337365 (0.008168) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 200}
0.336909 (0.008918) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 250}
0.339874 (0.007324) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 300}
0.339417 (0.007705) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 350}
0.341013 (0.004603) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 400}
0.343979 (0.004645) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 450}
0.343979 (0.004046) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 500}
0.332118 (0.002735) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 50}
0.333715 (0.005242) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 100}
0.337821 (0.007613) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 150}
0.336225 (0.007063) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 200}
0.337365 (0.008049) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 250}
0.339874 (0.007871) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 300}
0.340786 (0.005127) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 350}
0.341013 (0.003932) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 400}
0.343979 (0.004645) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 450}
0.343294 (0.004430) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 500}
0.330977 (0.002919) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 50}
0.332804 (0.008367) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 100}
0.334855 (0.008216) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 150}
0.334400 (0.008788) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 200}
0.335997 (0.009990) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 250}
0.338962 (0.008827) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 300}
0.340786 (0.006072) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 350}
0.342382 (0.004271) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 400}
0.343751 (0.005839) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 450}
0.343979 (0.005836) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 500}
0.333714 (0.005466) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 50}
0.335540 (0.004586) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 100}
0.339189 (0.005703) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 150}
0.341242 (0.004230) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 200}
0.337821 (0.008557) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 250}
0.341014 (0.007180) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 300}
0.342382 (0.004966) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 350}
0.342610 (0.004155) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 400}
0.344891 (0.004849) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 450}
0.345347 (0.004496) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 500}
0.332346 (0.004398) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 50}
0.335768 (0.005026) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 100}
0.339645 (0.005794) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 150}
0.339645 (0.004498) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 200}
0.337365 (0.009092) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 250}
0.341471 (0.006788) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 300}
0.342610 (0.004648) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 350}
0.342610 (0.004155) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 400}
0.345347 (0.005092) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 450}
0.345575 (0.004640) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 500}
0.331205 (0.002264) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 50}
0.331891 (0.006360) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 100}
0.337820 (0.006023) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 150}
0.337365 (0.008168) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 200}
0.336909 (0.008918) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 250}
0.339874 (0.007324) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 300}
0.339417 (0.007705) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 350}
0.341013 (0.004603) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 400}
0.343979 (0.004645) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 450}
0.343979 (0.004046) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 500}
0.332118 (0.002735) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 50}
0.333715 (0.005242) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 100}
0.337821 (0.007613) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 150}
0.336225 (0.007063) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 200}
0.337365 (0.008049) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 250}
0.339874 (0.007871) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 300}
0.340786 (0.005127) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 350}
0.341013 (0.003932) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 400}
0.343979 (0.004645) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 450}
0.343294 (0.004430) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 500}
0.330977 (0.002919) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 50}
0.332804 (0.008367) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 100}
0.334855 (0.008216) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 150}
0.334400 (0.008788) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 200}
0.335997 (0.009990) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 250}
0.338962 (0.008827) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 300}
0.340786 (0.006072) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 350}
0.342382 (0.004271) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 400}
0.343751 (0.005839) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 450}
0.343979 (0.005836) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 500}
0.316150 (0.006842) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 50}
0.320712 (0.007644) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 100}
0.326872 (0.009561) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 150}
0.326188 (0.011975) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 200}
0.328014 (0.008499) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 250}
0.327786 (0.008938) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 300}
0.326189 (0.008982) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 350}
0.328013 (0.008578) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 400}
0.327101 (0.010364) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 450}
0.330066 (0.007243) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 500}
0.316150 (0.006842) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 50}
0.320712 (0.007644) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 100}
0.326188 (0.009386) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 150}
0.325732 (0.012163) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 200}
0.327786 (0.008501) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 250}
0.326417 (0.007870) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 300}
0.325505 (0.008570) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 350}
0.327101 (0.008240) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 400}
0.326189 (0.009978) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 450}
0.329838 (0.007486) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 500}
0.315466 (0.007543) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 50}
0.319572 (0.008734) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 100}
0.325504 (0.009653) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 150}
0.325504 (0.011905) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 200}
0.327558 (0.008466) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 250}
0.326873 (0.008164) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 300}
0.326189 (0.009434) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 350}
0.327329 (0.008566) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 400}
0.326873 (0.010668) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 450}
0.329382 (0.008027) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 500}
0.314098 (0.009039) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 50}
0.317292 (0.010258) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 100}
0.323908 (0.010020) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 150}
0.323451 (0.012486) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 200}
0.325734 (0.011116) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 250}
0.325733 (0.009788) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 300}
0.325277 (0.008757) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 350}
0.326645 (0.008027) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 400}
0.325961 (0.009779) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 450}
0.328469 (0.007130) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 500}
0.311817 (0.008341) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 50}
0.315238 (0.009679) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 100}
0.320941 (0.008608) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 150}
0.321169 (0.011297) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 200}
0.322539 (0.008629) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 250}
0.322310 (0.006983) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 300}
0.321398 (0.007794) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 350}
0.322994 (0.007472) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 400}
0.322310 (0.009696) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 450}
0.324591 (0.006921) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 500}
0.365419 (0.003801) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 50}

0.366560 (0.006441) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 200}
0.366560 (0.006441) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 250}
0.367473 (0.005068) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 300}
0.367017 (0.005838) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 350}
0.365876 (0.005577) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 400}
0.365876 (0.005289) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 450}
0.366332 (0.005540) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 1, 'n_estimators': 500}
0.367244 (0.004054) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 50}
0.367016 (0.006806) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 100}
0.366787 (0.005740) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 150}
0.366789 (0.004827) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 200}
0.367929 (0.005834) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 250}
0.368157 (0.004738) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 300}
0.368157 (0.004738) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 350}
0.367245 (0.004507) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 400}
0.366560 (0.004191) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 450}
0.367017 (0.004113) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 2, 'n_estimators': 500}
0.366331 (0.003453) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 50}
0.365647 (0.005236) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 100}
0.366559 (0.005698) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 150}
0.366331 (0.006003) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 200}
0.366787 (0.006134) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 250}
0.367701 (0.004885) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 300}
0.367701 (0.004438) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 350}
0.366560 (0.004569) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 400}
0.366560 (0.004569) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 450}
0.367245 (0.004315) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 3, 'n_estimators': 500}
0.364735 (0.004276) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 50}
0.365192 (0.005650) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 100}
0.365420 (0.004976) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 150}
0.364964 (0.005447) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 200}
0.366105 (0.006025) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 250}
0.365649 (0.005277) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 300}
0.365192 (0.004970) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 350}
0.364507 (0.004662) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 400}
0.364736 (0.004812) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 450}
0.363823 (0.004106) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 4, 'n_estimators': 500}
0.363366 (0.004249) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 50}
0.364508 (0.006294) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 100}
0.364051 (0.004804) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 150}
0.363823 (0.005203) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 200}
0.363823 (0.005203) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 250}
0.364052 (0.005420) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 300}
0.364052 (0.005420) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 350}
0.363596 (0.005010) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 400}
0.363139 (0.004831) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 450}
0.363139 (0.004831) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'auto', 'min_samples_leaf': 5, 'n_estimators': 500}
0.366559 (0.004860) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 50}
0.366787 (0.007188) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 100}
0.366559 (0.006179) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 150}
0.366560 (0.006441) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 200}
0.366560 (0.006441) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 250}
0.367473 (0.005068) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 300}
0.367017 (0.005838) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 350}
0.365876 (0.005577) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 400}
0.365876 (0.005289) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 450}
0.366332 (0.005540) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 500}
0.367244 (0.004054) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 50}
0.367016 (0.006806) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 100}
0.366787 (0.005740) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 150}
0.366789 (0.004827) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 200}
0.367929 (0.005834) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 250}
0.368157 (0.004738) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 300}
0.368157 (0.004738) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 350}
0.367245 (0.004507) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 400}
0.366560 (0.004191) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 450}
0.367017 (0.004113) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 500}
0.366331 (0.003453) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 50}
0.365647 (0.005236) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 100}
0.366559 (0.005698) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 150}
0.366331 (0.006003) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 200}
0.366787 (0.006134) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 250}
0.367701 (0.004885) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 300}
0.367701 (0.004438) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 350}
0.366560 (0.004569) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 400}
0.366560 (0.004569) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 450}
0.367245 (0.004315) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 500}
0.364735 (0.004276) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 50}
0.365192 (0.005650) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 100}
0.365420 (0.004976) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 150}
0.364964 (0.005447) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 200}
0.366105 (0.006025) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 250}
0.365649 (0.005277) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 300}
0.365192 (0.004970) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 350}
0.364507 (0.004662) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 400}
0.364736 (0.004812) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 450}
0.363823 (0.004106) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 500}
0.363366 (0.004249) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 50}
0.364508 (0.006294) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 100}
0.364051 (0.004804) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 150}
0.363823 (0.005203) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 200}
0.363823 (0.005203) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 250}
0.364052 (0.005420) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 300}
0.364052 (0.005420) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 350}
0.363596 (0.005010) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 400}
0.363139 (0.004831) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 450}
0.363139 (0.004831) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 500}
0.365875 (0.004232) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 50}
0.366103 (0.006449) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 100}
0.365875 (0.005465) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 150}
0.365647 (0.005496) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 200}
0.365876 (0.005760) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 250}
0.366789 (0.004375) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 300}
0.366332 (0.005188) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 350}
0.365191 (0.004839) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 400}
0.364963 (0.004368) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 450}
0.365192 (0.004350) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 500}
0.366331 (0.003627) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 50}
0.366331 (0.006046) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 100}
0.366103 (0.004994) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 150}
0.366104 (0.005217) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 200}
0.366331 (0.005411) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 250}
0.367016 (0.003617) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 300}
0.367016 (0.003617) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 350}
0.365419 (0.003662) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 400}
0.365647 (0.003585) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 450}
0.365647 (0.003538) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 500}
0.364734 (0.004289) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 50}
0.364050 (0.006474) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 100}
0.363822 (0.005213) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 150}
0.363594 (0.005479) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 200}
0.364050 (0.005567) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 250}
0.364279 (0.003155) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 300}
0.365419 (0.003687) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 350}
0.364050 (0.005078) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 400}
0.363594 (0.004311) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 450}
0.363594 (0.003663) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 500}
0.360856 (0.004998) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 50}
0.361085 (0.005947) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 100}
0.360857 (0.005590) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 150}
0.361998 (0.005338) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 200}
0.362454 (0.003979) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 250}
0.362455 (0.003346) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 300}
0.361998 (0.003713) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 350}
0.361541 (0.003676) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 400}
0.361542 (0.003839) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 450}
0.361313 (0.003519) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 500}
0.359259 (0.004594) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 50}
0.359488 (0.006382) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 100}
0.359260 (0.005347) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 150}
0.359032 (0.005699) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 200}
0.360173 (0.004434) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 250}
0.360858 (0.003049) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 300}
0.360858 (0.003049) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 350}
0.360173 (0.003127) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 400}
0.360173 (0.003127) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 450}
0.360173 (0.003127) with: {'criterion': 'entropy', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 500}

In [32]:
# fit final model
# final_model = RandomForestClassifier(n_estimators=450, max_depth=None)
final_model = RandomForestClassifier(criterion='entropy', max_depth=10, max_features='auto', min_samples_leaf= 2, n_estimators=300, n_jobs=2, random_state=1)
final_model.fit(X_train, y_train)

y_pred = final_model.predict(X_test)

In [33]:
# train test accuracy score
print("train accuracy: {}, test accuracy: {}".format(round(final_model.score(X_train, y_train), 3), round(final_model.score(X_test, y_test), 3)))

train accuracy: 0.38, test accuracy: 0.376

In [34]:
# classification report
print(classification_report(y_test, y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.889     1.000     0.941         8
           1      0.000     0.000     0.000         8
           2      0.000     0.000     0.000         8
           3      0.800     1.000     0.889         8
           4      0.000     0.000     0.000         8
           5      0.727     1.000     0.842         8
           6      0.000     0.000     0.000         8
           7      0.214     0.375     0.273         8
           8      0.444     1.000     0.615         8
           9      0.714     0.625     0.667         8
          10      0.400     1.000     0.571         8
          11      0.296     1.000     0.457         8
          12      0.000     0.000     0.000         8
          13      0.500     0.375     0.429         8
          14      0.500     0.375     0.429         8
          15      0.000     0.000     0.000         8
          16      0.364     1.000     0.533         8
          17      0.421     1.000     0.593         8
          18      0.308     0.500     0.381         8
          19      1.000     0.500     0.667         8
          20      0.333     0.250     0.286         8
          21      0.320     1.000     0.485         8
          22      0.000     0.000     0.000         8
          23      0.800     1.000     0.889         8
          24      0.000     0.000     0.000         8
          25      0.229     1.000     0.372         8
          26      0.131     1.000     0.232         8
          27      0.000     0.000     0.000         8
          28      0.615     1.000     0.762         8
          29      0.000     0.000     0.000         8
          30      1.000     0.625     0.769         8
          31      0.000     0.000     0.000         8
          32      0.000     0.000     0.000         8
          33      0.000     0.000     0.000         8
          34      0.500     0.250     0.333         8
          35      0.000     0.000     0.000         8
          36      0.000     0.000     0.000         8
          37      1.000     0.875     0.933         8
          38      0.000     0.000     0.000         8
          39      0.000     0.000     0.000         8
          40      0.000     0.000     0.000         8
          41      0.000     0.000     0.000         8
          42      0.154     0.250     0.190         8
          43      0.000     0.000     0.000         8
          44      0.000     0.000     0.000         8
          45      1.000     0.125     0.222         8
          46      0.533     1.000     0.696         8
          47      0.000     0.000     0.000         8
          48      1.000     0.375     0.545         8
          49      0.000     0.000     0.000         8
          50      0.000     0.000     0.000         8
          51      0.000     0.000     0.000         8
          52      0.444     1.000     0.615         8
          53      0.000     0.000     0.000         8
          54      0.000     0.000     0.000         8
          55      0.160     1.000     0.276         8
          56      0.000     0.000     0.000         8
          57      0.000     0.000     0.000         8
          58      0.357     0.625     0.455         8
          59      0.116     1.000     0.208         8
          60      0.000     0.000     0.000         8
          61      0.571     0.500     0.533         8
          62      0.333     0.500     0.400         8
          63      1.000     0.125     0.222         8
          64      0.000     0.000     0.000         8
          65      0.178     1.000     0.302         8
          66      0.000     0.000     0.000         8
          67      0.276     1.000     0.432         8
          68      0.000     0.000     0.000         8
          69      0.222     1.000     0.364         8
          70      1.000     0.125     0.222         8
          71      0.727     1.000     0.842         8
          72      0.000     0.000     0.000         8
          73      0.500     1.000     0.667         8
          74      0.667     0.500     0.571         8
          75      0.000     0.000     0.000         8
          76      0.571     1.000     0.727         8
          77      0.300     0.375     0.333         8
          78      1.000     1.000     1.000         8
          79      0.800     0.500     0.615         8
          80      1.000     0.625     0.769         8
          81      0.889     1.000     0.941         8
          82      0.000     0.000     0.000         8
          83      0.000     0.000     0.000         8
          84      0.000     0.000     0.000         8
          85      0.000     0.000     0.000         8
          86      0.000     0.000     0.000         8
          87      0.800     1.000     0.889         8
          88      0.148     1.000     0.258         8
          89      1.000     0.500     0.667         8
          90      0.000     0.000     0.000         8
          91      0.467     0.875     0.609         8
          92      0.000     0.000     0.000         8
          93      0.000     0.000     0.000         8
          94      0.000     0.000     0.000         8
          95      0.000     0.000     0.000         8
          96      1.000     1.000     1.000         8
          97      0.151     1.000     0.262         8
          98      0.500     0.500     0.500         8
          99      0.000     0.000     0.000         8
         100      0.258     1.000     0.410         8
         101      0.000     0.000     0.000         8
         102      1.000     1.000     1.000         8
         103      0.000     0.000     0.000         8
         104      0.000     0.000     0.000         8
         105      0.000     0.000     0.000         8
         106      0.667     1.000     0.800         8
         107      0.000     0.000     0.000         8
         108      0.000     0.000     0.000         8
         109      0.000     0.000     0.000         8
         110      0.667     0.250     0.364         8
         111      0.000     0.000     0.000         8
         112      0.000     0.000     0.000         8
         113      0.000     0.000     0.000         8
         114      0.571     1.000     0.727         8
         115      0.500     0.625     0.556         8
         116      1.000     0.625     0.769         8
         117      0.000     0.000     0.000         8
         118      0.000     0.000     0.000         8
         119      0.000     0.000     0.000         8
         120      0.000     0.000     0.000         8
         121      0.000     0.000     0.000         8
         122      0.000     0.000     0.000         8
         123      0.333     0.625     0.435         8
         124      0.000     0.000     0.000         8
         125      0.000     0.000     0.000         8
         126      1.000     0.625     0.769         8
         127      0.000     0.000     0.000         8
         128      1.000     1.000     1.000         8
         129      0.000     0.000     0.000         8
         130      1.000     0.250     0.400         8
         131      0.000     0.000     0.000         8
         132      0.600     0.375     0.462         8
         133      0.286     1.000     0.444         8
         134      0.000     0.000     0.000         8
         135      0.205     1.000     0.340         8
         136      0.778     0.875     0.824         8

    accuracy                          0.376      1096
   macro avg      0.294     0.376     0.285      1096
weighted avg      0.294     0.376     0.285      1096

D:\ProgramFiles\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramFiles\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\ProgramFiles\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

# Prediction Testing

final_model.predict testing

In [60]:
final_prediction = final_model.predict([[6,1,1,1,1]])
final_prediction

array([55])

In [108]:
# inverse transform predicted class
print(lbl_encoder.inverse_transform(final_prediction)[0])

Discoaster indica

final_model.predict_proba testing

In [103]:
probs = final_model.predict_proba([[6,1,1,1,1]])
probs

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01751951, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.05687604, 0.        , 0.        ,
        0.        , 0.04613404, 0.        , 0.        , 0.        ,
        0.09742517, 0.04006039, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.07435707, 0.        , 0.04942489,
        0.        , 0.        , 0.        , 0.14384469, 0.        ,
        0.14466725, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.1415474 , 0.        , 0.        ,
        0.        , 0.04421717, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.14392636, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [36]:
# sort prediction probabilitises
sorted_probs = sorted(probs[0], reverse=True)
sorted_probs

[0.14466724897777275,
 0.1439263612153023,
 0.14384469308615638,
 0.141547403528086,
 0.09742517034707833,
 0.07435707438821167,
 0.05687604069877342,
 0.0494248946057046,
 0.04613403962281774,
 0.04421716932743468,
 0.040060389326656516,
 0.017519514876005438,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [37]:
# search top three prediction probabilities
top_three_probs = [sorted_probs[0], sorted_probs[1], sorted_probs[2]]
top_three_probs

[0.14466724897777275, 0.1439263612153023, 0.14384469308615638]

In [105]:
# search best three prediction class
best_n = np.argsort(probs)[:,-3:]
best_n[0]

array([ 53, 111,  55], dtype=int64)

In [106]:
# rank best three prediction class from the best
best_three_species = [best_n[0][2], best_n[0][1], best_n[0][0]]
best_three_species

[55, 111, 53]

In [107]:
# inverse transform ranked best three predicted class
lbl_encoder.inverse_transform(best_three_species)

array(['Discoaster indica', 'Discoaster sanmiguelensis',
       'Discoaster icarus'], dtype=object)

# Saving Models

In [42]:
# save trained random forest model
save_model(final_model, "random_forest_nannomate.pkl")

Model is pickled as model/random_forest_nannomate.pkl

In [43]:
# save label encoder
save_model(lbl_encoder, "lbl_encoder_nannomate.pkl")

Model is pickled as model/lbl_encoder_nannomate.pkl

In [44]:
# save ordinal encoder
save_model(ordl_encoder, "ordl_encoder_nannomate.pkl")

Model is pickled as model/ordl_encoder_nannomate.pkl

In [45]:
from jcopml.utils import load_model
loaded_model = load_model("model/random_forest_nannomate.pkl")
loaded_encoder = load_model("model/lbl_encoder_nannomate.pkl")

In [46]:
loaded_model.predict_proba([[6,1,1,1,1]])[0][53]

0.14384469308615638

In [47]:
loaded_model.predict([[6,1,1,1,1]])[0]

55

In [48]:
print(loaded_encoder.inverse_transform(loaded_model.predict([[6,1,1,1,1]]))[0])

Discoaster indica

Features reference

In [ ]:
ordl_encoder.inverse_transform([['Bercabang', 'Knob', 'Bentuk_Lengan', 'Ujung_Lengan']])

In [37]:
ordl_encoder.inverse_transform([[0, 0, 0, 0]])

array([['Tidak', 'Tidak', 'Pipih', 'Lancip']], dtype=object)

In [34]:
ordl_encoder.inverse_transform([[1, 1, 1, 1]])

array([['Ya', 'Ya', 'Tebal', 'Tumpul']], dtype=object)