# Import library

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from collections import Counter
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import top_k_accuracy_score
from jcopml.utils import save_model
from jcopml.utils import load_model

# Data preprocessing

In [2]:
# read data
df = pd.read_csv('Dataset_Discoaster(Tree)-Neogene-Resample.csv')
df

,Jumlah_Lengan,Bercabang,Simetris,Knob,Ukuran_Lengan,Bentuk_Lengan,Ujung_Lengan,Ujung_Lengan_Melengkung,Spesies
0,3,Ya,Ya,Tidak,Panjang,Pipih,Lancip,Tidak,Discoaster triradiatus
1,4,Tidak,Ya,Tidak,Pendek,Pipih,Tumpul,Tidak,Discoaster tamalis
2,4,Tidak,Tidak,Tidak,Pendek,Pipih,Lancip,Tidak,Discoaster alyssae
3,5,Tidak,Tidak,Ya,Panjang,Pipih,Lancip,Tidak,Discoaster asymmetricus
4,5,Ya,Tidak,Tidak,Panjang,Pipih,Lancip,Tidak,Discoaster pentaradiatus
5,5,Ya,Tidak,Tidak,Panjang,Tebal,Lancip,Tidak,Discoaster prepentaradiatus
6,5,Tidak,Ya,Tidak,Panjang,Pipih,Lancip,Ya,Discoaster hamatus
7,5,Tidak,Ya,Tidak,Pendek,Pipih,Tumpul,Tidak,Discoaster bellus
8,5,Tidak,Ya,Ya,Panjang,Pipih,Tumpul,Tidak,Discoaster quinqueramus
9,5,Tidak,Ya,Ya,Pendek,Pipih,Tumpul,Tidak,Discoaster berggrenii
10,5,Tidak,Ya,Ya,Pendek,Pipih,Tumpul,Tidak,Discoaster consutus
11,5,Tidak,Ya,Ya,Pendek,Pipih,Tumpul,Tidak,Discoaster bergenii
12,6,Tidak,Ya,Ya,Panjang,Pipih,Lancip,Tidak,Discoaster brouweri
13,6,Tidak,Ya,Ya,Panjang,Pipih,Lancip,Tidak,Discoaster altus
14,6,Tidak,Tidak,Ya,Panjang,Pipih,Lancip,Ya,Discoaster calcaris
15,6,Tidak,Ya,Ya,Panjang,Pipih,Tumpul,Tidak,Discoaster braarudii
16,6,Tidak,Ya,Ya,Panjang,Pipih,Lancip,Tidak,Discoaster neorectus
17,6,Tidak,Ya,Ya,Pendek,Pipih,Lancip,Tidak,Discoaster dennei
18,6,Tidak,Ya,Ya,Pendek,Pipih,Tumpul,Tidak,Discoaster formosus
19,6,Tidak,Ya,Tidak,Pendek,Tebal,Tumpul,Tidak,Discoaster pliostellulus
20,6,Ya,Tidak,Tidak,Panjang,Pipih,Tumpul,Tidak,Discoaster surculus
21,6,Ya,Ya,Ya,Panjang,Pipih,Tumpul,Tidak,Discoaster pseudovariabilis
22,6,Ya,Ya,Ya,Panjang,Pipih,Tumpul,Tidak,Discoaster subsurculus
23,6,Ya,Tidak,Ya,Panjang,Pipih,Tumpul,Tidak,Discoaster variabilis
24,6,Tidak,Tidak,Tidak,Panjang,Pipih,Lancip,Ya,Discoaster loeblichii
25,6,Ya,Ya,Ya,Pendek,Tebal,Lancip,Tidak,Discoaster mendomobensis
26,6,Ya,Ya,Ya,Panjang,Pipih,Tumpul,Tidak,Discoaster exilis
27,6,Ya,Ya,Ya,Panjang,Pipih,Tumpul,Tidak,Discoaster bollii
28,6,Ya,Ya,Ya,Panjang,Pipih,Tumpul,Tidak,Discoaster bollii
29,6,Ya,Ya,Ya,Panjang,Pipih,Tumpul,Tidak,Discoaster bollii
30,6,Ya,Ya,Ya,Panjang,Pipih,Tumpul,Tidak,Discoaster bollii
31,6,Ya,Ya,Ya,Panjang,Pipih,Tumpul,Tidak,Discoaster bollii
32,6,Ya,Ya,Ya,Pendek,Pipih,Tumpul,Tidak,Discoaster bollii
33,6,Ya,Ya,Ya,Pendek,Pipih,Tumpul,Tidak,Discoaster bollii
34,6,Ya,Ya,Ya,Pendek,Pipih,Tumpul,Tidak,Discoaster bollii
35,6,Ya,Ya,Ya,Pendek,Pipih,Tumpul,Tidak,Discoaster bollii
36,6,Ya,Ya,Ya,Pendek,Pipih,Tumpul,Tidak,Discoaster bollii
37,6,Ya,Ya,Ya,Panjang,Pipih,Lancip,Tidak,Discoaster petaliformis
38,6,Ya,Ya,Ya,Pendek,Tebal,Tumpul,Tidak,Discoaster sanmiguelensis
39,6,Ya,Tidak,Ya,Pendek,Tebal,Tumpul,Tidak,Discoaster musicus
40,6,Ya,Ya,Ya,Pendek,Pipih,Lancip,Tidak,Discoaster virginianus
41,6,Ya,Ya,Tidak,Pendek,Tebal,Tumpul,Tidak,Discoaster micros
42,6,Ya,Ya,Ya,Pendek,Tebal,Tumpul,Tidak,Discoaster deflandrei
43,6,Tidak,Tidak,Tidak,Pendek,Tebal,Tumpul,Tidak,Discoaster kugleri
44,6,Tidak,Tidak,Ya,Pendek,Tebal,Tumpul,Tidak,Discoaster druggii
45,6,Tidak,Tidak,Ya,Pendek,Tebal,Tumpul,Tidak,Discoaster druggii
46,6,Tidak,Tidak,Ya,Pendek,Tebal,Tumpul,Tidak,Discoaster druggii
47,6,Tidak,Tidak,Ya,Pendek,Tebal,Tumpul,Tidak,Discoaster druggii
48,6,Tidak,Tidak,Ya,Pendek,Tebal,Tumpul,Tidak,Discoaster druggii
49,6,Tidak,Tidak,Tidak,Pendek,Tebal,Tumpul,Tidak,Discoaster druggii
50,6,Tidak,Tidak,Tidak,Pendek,Tebal,Tumpul,Tidak,Discoaster druggii
51,6,Tidak,Tidak,Tidak,Pendek,Tebal,Tumpul,Tidak,Discoaster druggii
52,6,Tidak,Tidak,Tidak,Pendek,Tebal,Tumpul,Tidak,Discoaster druggii
53,6,Tidak,Tidak,Tidak,Pendek,Tebal,Tumpul,Tidak,Discoaster druggii
54,6,Tidak,Ya,Ya,Pendek,Tebal,Tumpul,Tidak,Discoaster adamanteus

In [3]:
df.shape

(55, 9)

In [4]:
# feautures encoding
ordl_encoder = preprocessing.OrdinalEncoder(dtype=int)
ordl_encoder.fit(df[['Bercabang', 'Simetris', 'Knob', 'Ukuran_Lengan', 'Bentuk_Lengan', 'Ujung_Lengan', 'Ujung_Lengan_Melengkung']])
df[['Bercabang', 'Simetris', 'Knob', 'Ukuran_Lengan', 'Bentuk_Lengan', 'Ujung_Lengan', 'Ujung_Lengan_Melengkung']] = ordl_encoder.transform(df[['Bercabang', 'Simetris', 'Knob', 'Ukuran_Lengan', 'Bentuk_Lengan', 'Ujung_Lengan', 'Ujung_Lengan_Melengkung']])

In [5]:
df.head()

,Jumlah_Lengan,Bercabang,Simetris,Knob,Ukuran_Lengan,Bentuk_Lengan,Ujung_Lengan,Ujung_Lengan_Melengkung,Spesies
0,3,1,1,0,0,0,0,0,Discoaster triradiatus
1,4,0,1,0,1,0,1,0,Discoaster tamalis
2,4,0,0,0,1,0,0,0,Discoaster alyssae
3,5,0,0,1,0,0,0,0,Discoaster asymmetricus
4,5,1,0,0,0,0,0,0,Discoaster pentaradiatus

In [6]:
# target label encoding
lbl_encoder = preprocessing.LabelEncoder()
lbl_encoder.fit(df['Spesies'])
df['Spesies'] = lbl_encoder.transform(df['Spesies'])

In [7]:
df.head()

,Jumlah_Lengan,Bercabang,Simetris,Knob,Ukuran_Lengan,Bentuk_Lengan,Ujung_Lengan,Ujung_Lengan_Melengkung,Spesies
0,3,1,1,0,0,0,0,0,34
1,4,0,1,0,1,0,1,0,33
2,4,0,0,0,1,0,0,0,2
3,5,0,0,1,0,0,0,0,3
4,5,1,0,0,0,0,0,0,24

In [8]:
df.shape

(55, 9)

In [9]:
# check dataset balance
sorted(df['Spesies'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36]

In [10]:
print(sorted(Counter(df['Spesies']).items()))

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 10), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 10), (15, 1), (16, 1), (17, 1), (18, 1), (19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 1), (33, 1), (34, 1), (35, 1), (36, 1)]

In [11]:
df['Spesies'].value_counts().describe()

count    37.000000
mean      1.486486
std       2.063191
min       1.000000
25%       1.000000
50%       1.000000
75%       1.000000
max      10.000000
Name: Spesies, dtype: float64

In [12]:
# features and targets split
X = df[['Jumlah_Lengan', 'Bercabang', 'Simetris', 'Knob', 'Ukuran_Lengan', 'Bentuk_Lengan', 'Ujung_Lengan', 'Ujung_Lengan_Melengkung']]
X

,Jumlah_Lengan,Bercabang,Simetris,Knob,Ukuran_Lengan,Bentuk_Lengan,Ujung_Lengan,Ujung_Lengan_Melengkung
0,3,1,1,0,0,0,0,0
1,4,0,1,0,1,0,1,0
2,4,0,0,0,1,0,0,0
3,5,0,0,1,0,0,0,0
4,5,1,0,0,0,0,0,0
5,5,1,0,0,0,1,0,0
6,5,0,1,0,0,0,0,1
7,5,0,1,0,1,0,1,0
8,5,0,1,1,0,0,1,0
9,5,0,1,1,1,0,1,0
10,5,0,1,1,1,0,1,0
11,5,0,1,1,1,0,1,0
12,6,0,1,1,0,0,0,0
13,6,0,1,1,0,0,0,0
14,6,0,0,1,0,0,0,1
15,6,0,1,1,0,0,1,0
16,6,0,1,1,0,0,0,0
17,6,0,1,1,1,0,0,0
18,6,0,1,1,1,0,1,0
19,6,0,1,0,1,1,1,0
20,6,1,0,0,0,0,1,0
21,6,1,1,1,0,0,1,0
22,6,1,1,1,0,0,1,0
23,6,1,0,1,0,0,1,0
24,6,0,0,0,0,0,0,1
25,6,1,1,1,1,1,0,0
26,6,1,1,1,0,0,1,0
27,6,1,1,1,0,0,1,0
28,6,1,1,1,0,0,1,0
29,6,1,1,1,0,0,1,0
30,6,1,1,1,0,0,1,0
31,6,1,1,1,0,0,1,0
32,6,1,1,1,1,0,1,0
33,6,1,1,1,1,0,1,0
34,6,1,1,1,1,0,1,0
35,6,1,1,1,1,0,1,0
36,6,1,1,1,1,0,1,0
37,6,1,1,1,0,0,0,0
38,6,1,1,1,1,1,1,0
39,6,1,0,1,1,1,1,0
40,6,1,1,1,1,0,0,0
41,6,1,1,0,1,1,1,0
42,6,1,1,1,1,1,1,0
43,6,0,0,0,1,1,1,0
44,6,0,0,1,1,1,1,0
45,6,0,0,1,1,1,1,0
46,6,0,0,1,1,1,1,0
47,6,0,0,1,1,1,1,0
48,6,0,0,1,1,1,1,0
49,6,0,0,0,1,1,1,0
50,6,0,0,0,1,1,1,0
51,6,0,0,0,1,1,1,0
52,6,0,0,0,1,1,1,0
53,6,0,0,0,1,1,1,0
54,6,0,1,1,1,1,1,0

In [13]:
y = df['Spesies']
y

0     34
1     33
2      2
3      3
4     24
5     27
6     17
7      4
8     29
9      6
10    11
11     5
12     9
13     1
14    10
15     8
16    23
17    13
18    16
19    26
20    32
21    28
22    31
23    35
24    19
25    20
26    15
27     7
28     7
29     7
30     7
31     7
32     7
33     7
34     7
35     7
36     7
37    25
38    30
39    22
40    36
41    21
42    12
43    18
44    14
45    14
46    14
47    14
48    14
49    14
50    14
51    14
52    14
53    14
54     0
Name: Spesies, dtype: int32

In [14]:
# random oversampling
ros = RandomOverSampler(random_state=0)
X_resampled, y_resampled = ros.fit_resample(X, y)

In [15]:
# repeat check dataset balance
X_resampled

,Jumlah_Lengan,Bercabang,Simetris,Knob,Ukuran_Lengan,Bentuk_Lengan,Ujung_Lengan,Ujung_Lengan_Melengkung
0,3,1,1,0,0,0,0,0
1,4,0,1,0,1,0,1,0
2,4,0,0,0,1,0,0,0
3,5,0,0,1,0,0,0,0
4,5,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
365,6,1,1,1,1,0,0,0
366,6,1,1,1,1,0,0,0
367,6,1,1,1,1,0,0,0
368,6,1,1,1,1,0,0,0
369,6,1,1,1,1,0,0,0

In [16]:
y_resampled

0      34
1      33
2       2
3       3
4      24
       ..
365    36
366    36
367    36
368    36
369    36
Name: Spesies, Length: 370, dtype: int32

In [17]:
print(sorted(Counter(y_resampled).items()))

[(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 10), (6, 10), (7, 10), (8, 10), (9, 10), (10, 10), (11, 10), (12, 10), (13, 10), (14, 10), (15, 10), (16, 10), (17, 10), (18, 10), (19, 10), (20, 10), (21, 10), (22, 10), (23, 10), (24, 10), (25, 10), (26, 10), (27, 10), (28, 10), (29, 10), (30, 10), (31, 10), (32, 10), (33, 10), (34, 10), (35, 10), (36, 10)]

In [18]:
y_resampled.value_counts().describe()

count    37.0
mean     10.0
std       0.0
min      10.0
25%      10.0
50%      10.0
75%      10.0
max      10.0
Name: Spesies, dtype: float64

Train Test Split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.3, random_state=1945, stratify=y_resampled)

In [20]:
print(sorted(Counter(y_train).items()))

[(0, 7), (1, 7), (2, 7), (3, 7), (4, 7), (5, 7), (6, 7), (7, 7), (8, 7), (9, 7), (10, 7), (11, 7), (12, 7), (13, 7), (14, 7), (15, 7), (16, 7), (17, 7), (18, 7), (19, 7), (20, 7), (21, 7), (22, 7), (23, 7), (24, 7), (25, 7), (26, 7), (27, 7), (28, 7), (29, 7), (30, 7), (31, 7), (32, 7), (33, 7), (34, 7), (35, 7), (36, 7)]

In [21]:
y_train.value_counts().describe()

count    37.0
mean      7.0
std       0.0
min       7.0
25%       7.0
50%       7.0
75%       7.0
max       7.0
Name: Spesies, dtype: float64

In [22]:
print(sorted(Counter(y_test).items()))

[(0, 3), (1, 3), (2, 3), (3, 3), (4, 3), (5, 3), (6, 3), (7, 3), (8, 3), (9, 3), (10, 3), (11, 3), (12, 3), (13, 3), (14, 3), (15, 3), (16, 3), (17, 3), (18, 3), (19, 3), (20, 3), (21, 3), (22, 3), (23, 3), (24, 3), (25, 3), (26, 3), (27, 3), (28, 3), (29, 3), (30, 3), (31, 3), (32, 3), (33, 3), (34, 3), (35, 3), (36, 3)]

In [23]:
y_test.value_counts().describe()

count    37.0
mean      3.0
std       0.0
min       3.0
25%       3.0
50%       3.0
75%       3.0
max       3.0
Name: Spesies, dtype: float64

# Algorithm Selection Test

## Support Vector Machine

In [24]:
# regularization parameter
C = [0.1, 1, 10, 100, 1000]
# kernel function
kernel = ['linear', 'poly', 'rbf', 'sigmoid']
# degree of the polynomial kernel function
degree = [2, 3, 4]
# kernel coefficient for 'rbf', 'poly' and 'sigmoid'.
gamma = ['scale', 'auto', 0.1, 1, 10]
# create the params grid
param_grid = {'C': C,
              'kernel': kernel,
               'degree': degree,
             'gamma': gamma}

In [25]:
# GridSearchCV fit
model = SVC(random_state=1)

grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring="accuracy", cv=4, verbose=3)
grid_result = grid.fit(X_train.values, y_train.values)

Fitting 4 folds for each of 300 candidates, totalling 1200 fits
[CV 1/4] END C=0.1, degree=2, gamma=scale, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=scale, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=scale, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=scale, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=scale, kernel=poly;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=scale, kernel=poly;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=scale, kernel=poly;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=scale, kernel=poly;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=scale, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=scale, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=scale, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=scale, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=scale, kernel=sigmoid;, score=0.077 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=scale, kernel=sigmoid;, score=0.062 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=scale, kernel=sigmoid;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=scale, kernel=sigmoid;, score=0.109 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=auto, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=auto, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=auto, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=auto, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=auto, kernel=poly;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=auto, kernel=poly;, score=0.385 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=auto, kernel=poly;, score=0.385 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=auto, kernel=poly;, score=0.516 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=auto, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=auto, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=auto, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=auto, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=0.1, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=0.1, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=0.1, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=0.1, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=0.1, kernel=poly;, score=0.323 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=0.1, kernel=poly;, score=0.169 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=0.1, kernel=poly;, score=0.262 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=0.1, kernel=poly;, score=0.266 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=0.1, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=0.1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=0.1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=0.1, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=1, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=1, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=1, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=1, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=1, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=1, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=10, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=10, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=10, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=10, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=10, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=10, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=10, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=10, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=0.1, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=0.1, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=0.1, degree=2, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=scale, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=scale, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=scale, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=scale, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=scale, kernel=poly;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=scale, kernel=poly;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=scale, kernel=poly;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=scale, kernel=poly;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=scale, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=scale, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=scale, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=scale, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=scale, kernel=sigmoid;, score=0.077 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=scale, kernel=sigmoid;, score=0.062 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=scale, kernel=sigmoid;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=scale, kernel=sigmoid;, score=0.109 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=auto, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=auto, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=auto, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=auto, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s

[CV 3/4] END C=0.1, degree=3, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=auto, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=auto, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=auto, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=auto, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=0.1, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=0.1, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=0.1, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=0.1, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=0.1, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=0.1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=0.1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=0.1, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=1, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=1, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=1, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=1, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=1, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=1, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=10, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=10, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=10, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=10, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=10, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=10, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=10, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=10, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=0.1, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=0.1, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=0.1, degree=3, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=scale, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=scale, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=scale, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=scale, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=scale, kernel=poly;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=scale, kernel=poly;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=scale, kernel=poly;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=scale, kernel=poly;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=scale, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=scale, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=scale, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=scale, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=scale, kernel=sigmoid;, score=0.077 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=scale, kernel=sigmoid;, score=0.062 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=scale, kernel=sigmoid;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=scale, kernel=sigmoid;, score=0.109 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=auto, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=auto, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=auto, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=auto, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=auto, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=auto, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=auto, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=auto, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=0.1, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=0.1, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=0.1, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=0.1, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s

[CV 1/4] END C=0.1, degree=4, gamma=0.1, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=0.1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=0.1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=0.1, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=1, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=1, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=1, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=1, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=1, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=1, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=10, kernel=linear;, score=0.492 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=10, kernel=linear;, score=0.354 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=10, kernel=linear;, score=0.415 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=10, kernel=linear;, score=0.422 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=10, kernel=rbf;, score=0.108 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=10, kernel=rbf;, score=0.138 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=10, kernel=rbf;, score=0.138 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=10, kernel=rbf;, score=0.141 total time=   0.0s
[CV 1/4] END C=0.1, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=0.1, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=0.1, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=0.1, degree=4, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=scale, kernel=poly;, score=0.492 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=scale, kernel=poly;, score=0.385 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=scale, kernel=poly;, score=0.385 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=scale, kernel=poly;, score=0.516 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=scale, kernel=rbf;, score=0.323 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=scale, kernel=rbf;, score=0.200 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=scale, kernel=rbf;, score=0.292 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=scale, kernel=rbf;, score=0.297 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=scale, kernel=sigmoid;, score=0.077 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=scale, kernel=sigmoid;, score=0.062 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=scale, kernel=sigmoid;, score=0.138 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=scale, kernel=sigmoid;, score=0.109 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=0.1, kernel=rbf;, score=0.492 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=0.1, kernel=rbf;, score=0.385 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=0.1, kernel=rbf;, score=0.446 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=0.1, kernel=rbf;, score=0.516 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s

[CV 4/4] END C=1, degree=2, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=1, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1, degree=2, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=scale, kernel=poly;, score=0.708 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=scale, kernel=poly;, score=0.662 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=scale, kernel=poly;, score=0.692 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=scale, kernel=rbf;, score=0.323 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=scale, kernel=rbf;, score=0.200 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=scale, kernel=rbf;, score=0.292 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=scale, kernel=rbf;, score=0.297 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=scale, kernel=sigmoid;, score=0.077 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=scale, kernel=sigmoid;, score=0.062 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=scale, kernel=sigmoid;, score=0.138 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=scale, kernel=sigmoid;, score=0.109 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=0.1, kernel=rbf;, score=0.492 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=0.1, kernel=rbf;, score=0.385 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=0.1, kernel=rbf;, score=0.446 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=0.1, kernel=rbf;, score=0.516 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=1, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1, degree=3, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=scale, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=scale, kernel=poly;, score=0.662 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=scale, kernel=poly;, score=0.692 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s

[CV 1/4] END C=1, degree=4, gamma=scale, kernel=rbf;, score=0.323 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=scale, kernel=rbf;, score=0.200 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=scale, kernel=rbf;, score=0.292 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=scale, kernel=rbf;, score=0.297 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=scale, kernel=sigmoid;, score=0.077 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=scale, kernel=sigmoid;, score=0.062 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=scale, kernel=sigmoid;, score=0.138 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=scale, kernel=sigmoid;, score=0.109 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=0.1, kernel=rbf;, score=0.492 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=0.1, kernel=rbf;, score=0.385 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=0.1, kernel=rbf;, score=0.446 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=0.1, kernel=rbf;, score=0.516 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=1, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1, degree=4, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=scale, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=scale, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=scale, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=scale, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=scale, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=scale, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=scale, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=scale, kernel=sigmoid;, score=0.108 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=scale, kernel=sigmoid;, score=0.062 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=scale, kernel=sigmoid;, score=0.169 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=scale, kernel=sigmoid;, score=0.141 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s

[CV 4/4] END C=10, degree=2, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=0.1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=0.1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=0.1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=0.1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=10, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=10, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=10, degree=2, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=scale, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=scale, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=scale, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=scale, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=scale, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=scale, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=scale, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=scale, kernel=sigmoid;, score=0.108 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=scale, kernel=sigmoid;, score=0.062 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=scale, kernel=sigmoid;, score=0.169 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=scale, kernel=sigmoid;, score=0.141 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=0.1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=0.1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=0.1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=0.1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=1, kernel=linear;, score=0.766 total time=   0.0s

[CV 1/4] END C=10, degree=3, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=10, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=10, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=10, degree=3, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=scale, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=scale, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=scale, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=scale, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=scale, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=scale, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=scale, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=scale, kernel=sigmoid;, score=0.108 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=scale, kernel=sigmoid;, score=0.062 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=scale, kernel=sigmoid;, score=0.169 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=scale, kernel=sigmoid;, score=0.141 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=0.1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=0.1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=0.1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=0.1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=10, degree=4, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=10, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=10, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s

[CV 3/4] END C=10, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=10, degree=4, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=scale, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=scale, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=scale, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=scale, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=scale, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=scale, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=scale, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=scale, kernel=sigmoid;, score=0.262 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=scale, kernel=sigmoid;, score=0.215 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=scale, kernel=sigmoid;, score=0.231 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=scale, kernel=sigmoid;, score=0.234 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=auto, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=auto, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=0.1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=0.1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=0.1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=0.1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=0.1, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=0.1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=100, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=100, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=100, degree=2, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=scale, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=scale, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=scale, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=scale, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=scale, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=scale, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=scale, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=scale, kernel=sigmoid;, score=0.262 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=scale, kernel=sigmoid;, score=0.215 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=scale, kernel=sigmoid;, score=0.231 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=scale, kernel=sigmoid;, score=0.234 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s

[CV 1/4] END C=100, degree=3, gamma=auto, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=auto, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=0.1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=0.1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=0.1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=0.1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=0.1, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=0.1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=100, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=100, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=100, degree=3, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=scale, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=scale, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=scale, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=scale, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=scale, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=scale, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=scale, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=scale, kernel=sigmoid;, score=0.262 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=scale, kernel=sigmoid;, score=0.215 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=scale, kernel=sigmoid;, score=0.231 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=scale, kernel=sigmoid;, score=0.234 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=auto, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=auto, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=0.1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=0.1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=0.1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=0.1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=0.1, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=0.1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=1, kernel=linear;, score=0.766 total time=   0.0s

[CV 1/4] END C=100, degree=4, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=100, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=100, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=100, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=100, degree=4, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=scale, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=scale, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=scale, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=scale, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=scale, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=scale, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=scale, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=scale, kernel=sigmoid;, score=0.262 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=scale, kernel=sigmoid;, score=0.215 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=scale, kernel=sigmoid;, score=0.231 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=scale, kernel=sigmoid;, score=0.234 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=auto, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=auto, kernel=sigmoid;, score=0.031 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=0.1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=0.1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=0.1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=0.1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=0.1, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=0.1, kernel=sigmoid;, score=0.047 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s

[CV 2/4] END C=1000, degree=2, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1000, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=1000, degree=2, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1000, degree=2, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=scale, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=scale, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=scale, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=scale, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=scale, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=scale, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=scale, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=scale, kernel=sigmoid;, score=0.262 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=scale, kernel=sigmoid;, score=0.215 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=scale, kernel=sigmoid;, score=0.231 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=scale, kernel=sigmoid;, score=0.234 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=auto, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=auto, kernel=sigmoid;, score=0.031 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=0.1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=0.1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=0.1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=0.1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=0.1, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=0.1, kernel=sigmoid;, score=0.047 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=10, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=10, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=10, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=10, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1000, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=1000, degree=3, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1000, degree=3, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=scale, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=scale, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=scale, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=scale, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=scale, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=scale, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=scale, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s

[CV 1/4] END C=1000, degree=4, gamma=scale, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=scale, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=scale, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=scale, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=scale, kernel=sigmoid;, score=0.262 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=scale, kernel=sigmoid;, score=0.215 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=scale, kernel=sigmoid;, score=0.231 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=scale, kernel=sigmoid;, score=0.234 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=auto, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=auto, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=auto, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=auto, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=auto, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=auto, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=auto, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=auto, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=auto, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=auto, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=auto, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=auto, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=auto, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=auto, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=auto, kernel=sigmoid;, score=0.031 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=0.1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=0.1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=0.1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=0.1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=0.1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=0.1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=0.1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=0.1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=0.1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=0.1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=0.1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=0.1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=0.1, kernel=sigmoid;, score=0.092 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=0.1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=0.1, kernel=sigmoid;, score=0.047 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=1, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=1, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=1, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=1, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=1, kernel=poly;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=1, kernel=poly;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=1, kernel=poly;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=1, kernel=poly;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=1, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=1, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=1, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=1, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=1, kernel=sigmoid;, score=0.000 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=1, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=1, kernel=sigmoid;, score=0.016 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=10, kernel=linear;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=10, kernel=linear;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=10, kernel=linear;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=10, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=10, kernel=poly;, score=0.769 total time=   1.2s
[CV 2/4] END C=1000, degree=4, gamma=10, kernel=poly;, score=0.723 total time=   1.0s
[CV 3/4] END C=1000, degree=4, gamma=10, kernel=poly;, score=0.754 total time=   1.1s
[CV 4/4] END C=1000, degree=4, gamma=10, kernel=poly;, score=0.766 total time=   0.9s
[CV 1/4] END C=1000, degree=4, gamma=10, kernel=rbf;, score=0.769 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=10, kernel=rbf;, score=0.723 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=10, kernel=rbf;, score=0.754 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=10, kernel=rbf;, score=0.766 total time=   0.0s
[CV 1/4] END C=1000, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 2/4] END C=1000, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 3/4] END C=1000, degree=4, gamma=10, kernel=sigmoid;, score=0.015 total time=   0.0s
[CV 4/4] END C=1000, degree=4, gamma=10, kernel=sigmoid;, score=0.016 total time=   0.0s

In [26]:
# GridSearchCV result
print("Best: {} using {}".format(round(grid_result.best_score_, 6), grid_result.best_params_)) 

means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']

for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.752945 using {'C': 0.1, 'degree': 2, 'gamma': 1, 'kernel': 'poly'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 2, 'gamma': 'scale', 'kernel': 'linear'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 2, 'gamma': 'scale', 'kernel': 'rbf'}
0.096575 (0.029716) with: {'C': 0.1, 'degree': 2, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 2, 'gamma': 'auto', 'kernel': 'linear'}
0.444291 (0.060242) with: {'C': 0.1, 'degree': 2, 'gamma': 'auto', 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 2, 'gamma': 'auto', 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 0.1, 'degree': 2, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 2, 'gamma': 0.1, 'kernel': 'linear'}
0.254868 (0.055105) with: {'C': 0.1, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 2, 'gamma': 0.1, 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 0.1, 'degree': 2, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 2, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 0.1, 'degree': 2, 'gamma': 1, 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 2, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 0.1, 'degree': 2, 'gamma': 1, 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 2, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 0.1, 'degree': 2, 'gamma': 10, 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 2, 'gamma': 10, 'kernel': 'rbf'}
0.015445 (0.000104) with: {'C': 0.1, 'degree': 2, 'gamma': 10, 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 3, 'gamma': 'scale', 'kernel': 'linear'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf'}
0.096575 (0.029716) with: {'C': 0.1, 'degree': 3, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 3, 'gamma': 'auto', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 0.1, 'degree': 3, 'gamma': 'auto', 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 3, 'gamma': 'auto', 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 0.1, 'degree': 3, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 3, 'gamma': 0.1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 0.1, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 3, 'gamma': 0.1, 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 0.1, 'degree': 3, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 3, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 0.1, 'degree': 3, 'gamma': 1, 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 3, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 0.1, 'degree': 3, 'gamma': 1, 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 3, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 0.1, 'degree': 3, 'gamma': 10, 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 3, 'gamma': 10, 'kernel': 'rbf'}
0.015445 (0.000104) with: {'C': 0.1, 'degree': 3, 'gamma': 10, 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 4, 'gamma': 'scale', 'kernel': 'linear'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 4, 'gamma': 'scale', 'kernel': 'rbf'}
0.096575 (0.029716) with: {'C': 0.1, 'degree': 4, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 4, 'gamma': 'auto', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 0.1, 'degree': 4, 'gamma': 'auto', 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 4, 'gamma': 'auto', 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 0.1, 'degree': 4, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 4, 'gamma': 0.1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 0.1, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 4, 'gamma': 0.1, 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 0.1, 'degree': 4, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 4, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 0.1, 'degree': 4, 'gamma': 1, 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 4, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 0.1, 'degree': 4, 'gamma': 1, 'kernel': 'sigmoid'}
0.420853 (0.049058) with: {'C': 0.1, 'degree': 4, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 0.1, 'degree': 4, 'gamma': 10, 'kernel': 'poly'}
0.131310 (0.013664) with: {'C': 0.1, 'degree': 4, 'gamma': 10, 'kernel': 'rbf'}
0.015445 (0.000104) with: {'C': 0.1, 'degree': 4, 'gamma': 10, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 'scale', 'kernel': 'linear'}
0.444291 (0.060242) with: {'C': 1, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'}
0.278065 (0.046575) with: {'C': 1, 'degree': 2, 'gamma': 'scale', 'kernel': 'rbf'}
0.096575 (0.029716) with: {'C': 1, 'degree': 2, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 'auto', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 'auto', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 'auto', 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 1, 'degree': 2, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 0.1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'}
0.459675 (0.050030) with: {'C': 1, 'degree': 2, 'gamma': 0.1, 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 1, 'degree': 2, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 1, 'degree': 2, 'gamma': 1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 10, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 1, 'degree': 2, 'gamma': 10, 'kernel': 'rbf'}
0.015445 (0.000104) with: {'C': 1, 'degree': 2, 'gamma': 10, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 'scale', 'kernel': 'linear'}
0.706791 (0.037815) with: {'C': 1, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'}
0.278065 (0.046575) with: {'C': 1, 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf'}
0.096575 (0.029716) with: {'C': 1, 'degree': 3, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 'auto', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 'auto', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 'auto', 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 1, 'degree': 3, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 0.1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'}
0.459675 (0.050030) with: {'C': 1, 'degree': 3, 'gamma': 0.1, 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 1, 'degree': 3, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 1, 'degree': 3, 'gamma': 1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 10, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 1, 'degree': 3, 'gamma': 10, 'kernel': 'rbf'}
0.015445 (0.000104) with: {'C': 1, 'degree': 3, 'gamma': 10, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 'scale', 'kernel': 'linear'}
0.722175 (0.046559) with: {'C': 1, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'}
0.278065 (0.046575) with: {'C': 1, 'degree': 4, 'gamma': 'scale', 'kernel': 'rbf'}
0.096575 (0.029716) with: {'C': 1, 'degree': 4, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 'auto', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 'auto', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 'auto', 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 1, 'degree': 4, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 0.1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'}
0.459675 (0.050030) with: {'C': 1, 'degree': 4, 'gamma': 0.1, 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 1, 'degree': 4, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 1, 'degree': 4, 'gamma': 1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 10, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 1, 'degree': 4, 'gamma': 10, 'kernel': 'rbf'}
0.015445 (0.000104) with: {'C': 1, 'degree': 4, 'gamma': 10, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 'scale', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 'scale', 'kernel': 'rbf'}
0.119772 (0.040056) with: {'C': 10, 'degree': 2, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 'auto', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 'auto', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 'auto', 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 10, 'degree': 2, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 0.1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 0.1, 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 10, 'degree': 2, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 10, 'degree': 2, 'gamma': 1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 10, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 2, 'gamma': 10, 'kernel': 'rbf'}
0.015445 (0.000104) with: {'C': 10, 'degree': 2, 'gamma': 10, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 'scale', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf'}
0.119772 (0.040056) with: {'C': 10, 'degree': 3, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 'auto', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 'auto', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 'auto', 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 10, 'degree': 3, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 0.1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 0.1, 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 10, 'degree': 3, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 10, 'degree': 3, 'gamma': 1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 10, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 3, 'gamma': 10, 'kernel': 'rbf'}
0.015445 (0.000104) with: {'C': 10, 'degree': 3, 'gamma': 10, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 'scale', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 'scale', 'kernel': 'rbf'}
0.119772 (0.040056) with: {'C': 10, 'degree': 4, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 'auto', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 'auto', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 'auto', 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 10, 'degree': 4, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 0.1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 0.1, 'kernel': 'rbf'}
0.000000 (0.000000) with: {'C': 10, 'degree': 4, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 10, 'degree': 4, 'gamma': 1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 10, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 10, 'degree': 4, 'gamma': 10, 'kernel': 'rbf'}
0.015445 (0.000104) with: {'C': 10, 'degree': 4, 'gamma': 10, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 'scale', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 'scale', 'kernel': 'rbf'}
0.235517 (0.016630) with: {'C': 100, 'degree': 2, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 'auto', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 'auto', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 'auto', 'kernel': 'rbf'}
0.026983 (0.038251) with: {'C': 100, 'degree': 2, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 0.1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 0.1, 'kernel': 'rbf'}
0.026983 (0.038251) with: {'C': 100, 'degree': 2, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 100, 'degree': 2, 'gamma': 1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 10, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 2, 'gamma': 10, 'kernel': 'rbf'}
0.015445 (0.000104) with: {'C': 100, 'degree': 2, 'gamma': 10, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 'scale', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf'}
0.235517 (0.016630) with: {'C': 100, 'degree': 3, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 'auto', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 'auto', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 'auto', 'kernel': 'rbf'}
0.026983 (0.038251) with: {'C': 100, 'degree': 3, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 0.1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 0.1, 'kernel': 'rbf'}
0.026983 (0.038251) with: {'C': 100, 'degree': 3, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 100, 'degree': 3, 'gamma': 1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 10, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 3, 'gamma': 10, 'kernel': 'rbf'}
0.015445 (0.000104) with: {'C': 100, 'degree': 3, 'gamma': 10, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 'scale', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 'scale', 'kernel': 'rbf'}
0.235517 (0.016630) with: {'C': 100, 'degree': 4, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 'auto', 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 'auto', 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 'auto', 'kernel': 'rbf'}
0.026983 (0.038251) with: {'C': 100, 'degree': 4, 'gamma': 'auto', 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 0.1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 0.1, 'kernel': 'rbf'}
0.026983 (0.038251) with: {'C': 100, 'degree': 4, 'gamma': 0.1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 1, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 1, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 1, 'kernel': 'rbf'}
0.011599 (0.006697) with: {'C': 100, 'degree': 4, 'gamma': 1, 'kernel': 'sigmoid'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 10, 'kernel': 'linear'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 10, 'kernel': 'poly'}
0.752945 (0.018158) with: {'C': 100, 'degree': 4, 'gamma': 10, 'kernel': 'rbf'}

In [27]:
# Support Vector Machine
svm = SVC(C=0.1, degree=2, gamma= 1, kernel='poly', random_state=1)
svm_cv_results = cross_val_score(svm, X_train, y_train, cv=4, verbose=3)

[CV] END ................................ score: (test=0.769) total time=   0.0s
[CV] END ................................ score: (test=0.723) total time=   0.0s
[CV] END ................................ score: (test=0.754) total time=   0.0s
[CV] END ................................ score: (test=0.766) total time=   0.0s

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

In [28]:
print("accuracy: {}, std: {}".format(svm_cv_results.mean(), svm_cv_results.std()))

accuracy: 0.7529447115384615, std: 0.018158488211042722

## Random Forest

In [29]:
# number of trees in random forest
n_estimators = [1, 2, 4, 8, 16, 32]
# split criterion
criterion = ["gini", "entropy"]
# maximum number of levels in tree
max_depth = [5, 10, 15, 20]
# max considered features per split
max_features = ["sqrt", "log2", None]
# min samples per leaf node
min_samples_leaf = [1, 2, 3, 4, 5]
# create the params grid
param_grid = {'n_estimators': n_estimators,
              'criterion': criterion,
               'max_depth': max_depth,
             'max_features': max_features,
             'min_samples_leaf': min_samples_leaf}

In [30]:
# GridSearchCV fit
model = RandomForestClassifier(n_jobs=4, random_state=1)

grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring="accuracy", cv=4, verbose=3)
grid_result = grid.fit(X_train.values, y_train.values)

Fitting 4 folds for each of 720 candidates, totalling 2880 fits
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.662 total time=   2.3s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.492 total time=   1.2s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.523 total time=   1.4s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.516 total time=   1.2s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.615 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.492 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.492 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.453 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.615 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.569 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.462 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.312 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s

[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.338 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.262 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.385 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.203 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.554 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.462 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.500 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.631 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.308 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.523 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.508 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.438 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.641 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.492 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s

[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.492 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.453 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.569 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.594 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.431 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.323 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.359 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.1s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.400 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.292 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.354 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.328 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.585 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.523 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.492 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.615 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s

[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.308 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.277 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.523 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.508 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.500 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.338 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.292 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.438 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.508 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.338 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.292 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.406 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.477 total time=   0.0s

[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.338 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.292 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.375 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.462 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.554 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.292 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.262 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.375 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.646 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.538 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.594 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.677 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s

[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.385 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.281 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.477 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.469 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.523 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.538 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.800 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.600 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s

[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.615 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.359 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.578 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.385 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.323 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.375 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.523 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.600 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.578 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.246 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.554 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.492 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.477 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.484 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.646 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.672 total time=   0.0s

[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.800 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.508 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.484 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.750 total time=   0.0s

[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.431 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.323 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.631 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.308 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.277 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.246 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.297 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.523 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.641 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.800 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s

[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.523 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.477 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.453 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.646 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.594 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s

[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.385 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.385 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.354 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.312 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.438 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.523 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.800 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.600 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.750 total time=   0.0s

[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.615 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.359 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.578 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.385 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.323 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.375 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.523 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.600 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.578 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s

[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.246 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.554 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.492 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.477 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.484 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.646 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.800 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s

[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.508 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.484 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.431 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.323 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.631 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.308 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.277 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.246 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.297 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.523 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.641 total time=   0.0s

[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.800 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.523 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s

[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.477 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.453 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.646 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.594 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.385 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.385 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.354 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.312 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.438 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.523 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.800 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s

[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.600 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.615 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.359 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.578 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.781 total time=   0.0s

[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.385 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.323 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.375 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.523 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.600 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.578 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.246 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.554 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.492 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.477 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.484 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.646 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.800 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s

[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.508 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.484 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.431 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.323 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.631 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.766 total time=   0.0s

[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.308 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.277 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.246 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.297 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.523 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.641 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.800 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s

[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.523 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.477 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.453 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.646 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.594 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.385 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.385 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.354 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.312 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.438 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.523 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.677 total time=   0.0s

[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=gini, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.594 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.492 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.538 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.400 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.500 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.631 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.578 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.754 total time=   0.0s

[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.338 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.323 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.323 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.375 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.585 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.523 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.492 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.500 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.631 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.277 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.391 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.508 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.641 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.600 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.677 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s

[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.677 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.538 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.547 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.600 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.615 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.415 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.438 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.431 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.369 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.391 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.508 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.600 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.672 total time=   0.0s

[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.281 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.453 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.554 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.600 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.797 total time=   0.1s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.641 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s

[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.523 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.422 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.508 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.547 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.615 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.354 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s

[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.344 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.400 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.431 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.469 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.538 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.641 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=5, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s

[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.477 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.547 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.385 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.415 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.354 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.406 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.569 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.277 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.391 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.538 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.641 total time=   0.0s

[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.631 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.600 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.385 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.656 total time=   0.0s

[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.400 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.391 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.569 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.554 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.578 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.646 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.281 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.508 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.453 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s

[CV 3/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.554 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.750 total time=   0.0s

[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.422 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.508 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.547 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.354 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.344 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.400 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.431 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.469 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.538 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.641 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=10, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s

[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.477 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.547 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s

[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.385 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.415 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.354 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.406 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.569 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.277 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.391 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.538 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.641 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.631 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.600 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s

[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.385 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.400 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.391 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.569 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.554 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.578 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.646 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.703 total time=   0.0s

[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.281 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.508 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.453 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s

[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.554 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.422 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.508 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.547 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s

[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.354 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.344 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.400 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.431 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.469 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.538 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.641 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=15, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=1;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=2;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=4;, score=0.797 total time=   0.0s

[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=2, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.477 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=1;, score=0.547 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=2;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=4;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=8;, score=0.719 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=3, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.385 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.415 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.354 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=1;, score=0.406 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.569 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=2;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=4;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.277 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=1;, score=0.266 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.462 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=2;, score=0.391 total time=   0.0s

[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.538 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=4;, score=0.641 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.631 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.600 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=sqrt, min_samples_leaf=5, n_estimators=32;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=1;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=2;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=16;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=2, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s

[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.585 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.385 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=1;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.631 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=2;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=4;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=16;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=3, n_estimators=32;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.400 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=1;, score=0.391 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.569 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.554 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=2;, score=0.578 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.646 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=4;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=8;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=4, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.292 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=1;, score=0.281 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.508 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=2;, score=0.453 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.692 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.569 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=4;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=8;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.785 total time=   0.0s

[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=16;, score=0.688 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=log2, min_samples_leaf=5, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.831 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=1;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=2;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=4;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=8;, score=0.812 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=16;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=1, n_estimators=32;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.815 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.646 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=1;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.738 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=2;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=4;, score=0.781 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=8;, score=0.797 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.754 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=2, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.662 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.554 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=1;, score=0.562 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.708 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.677 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=2;, score=0.656 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.738 total time=   0.0s

[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=4;, score=0.750 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=8;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.723 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=16;, score=0.734 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.769 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=3, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.492 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.446 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=1;, score=0.422 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.615 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.508 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.585 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=2;, score=0.547 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=4;, score=0.609 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.769 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=8;, score=0.703 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.785 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.692 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=16;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.738 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=4, n_estimators=32;, score=0.766 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.354 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.369 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.323 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=1;, score=0.344 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.400 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.431 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.431 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=2;, score=0.469 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.631 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.538 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.615 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=4;, score=0.531 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.677 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.646 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=8;, score=0.641 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.754 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.662 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=16;, score=0.672 total time=   0.0s
[CV 1/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 2/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.723 total time=   0.0s
[CV 3/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.708 total time=   0.0s
[CV 4/4] END criterion=entropy, max_depth=20, max_features=None, min_samples_leaf=5, n_estimators=32;, score=0.734 total time=   0.0s

In [31]:
# GridSearchCV result
print("Best: {} using {}".format(round(grid_result.best_score_, 6), grid_result.best_params_)) 

means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']

for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.776202 using {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 2}
0.548137 (0.066449) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 1}
0.714603 (0.077991) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 2}
0.741406 (0.026615) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 4}
0.768510 (0.033443) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 8}
0.764603 (0.028645) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 16}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 32}
0.524820 (0.080539) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 1}
0.691346 (0.076941) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 2}
0.718269 (0.043291) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 4}
0.756911 (0.034111) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 8}
0.756791 (0.022347) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 16}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 32}
0.443510 (0.091456) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 1}
0.617909 (0.041387) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 2}
0.718389 (0.042778) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 4}
0.749099 (0.019162) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 8}
0.752885 (0.021821) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 16}
0.760697 (0.022267) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 32}
0.296935 (0.069759) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 1}
0.521154 (0.042958) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 2}
0.664183 (0.021386) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 4}
0.722055 (0.044537) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 8}
0.729808 (0.015945) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 16}
0.752945 (0.018158) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 32}
0.289483 (0.015139) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 1}
0.482452 (0.034444) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 2}
0.633233 (0.039455) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 4}
0.667909 (0.017929) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 8}
0.725781 (0.018135) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 16}
0.756791 (0.019520) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 32}
0.544351 (0.088923) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 1}
0.714363 (0.048806) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 2}
0.749099 (0.015774) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 4}
0.764603 (0.028645) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 8}
0.764603 (0.028645) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 16}
0.760757 (0.026664) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 32}
0.517127 (0.103511) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 1}
0.648438 (0.083388) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 2}
0.714423 (0.039070) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 4}
0.737500 (0.034009) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 8}
0.752885 (0.021821) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 16}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 32}
0.432151 (0.112661) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 1}
0.609856 (0.065858) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 2}
0.679627 (0.064256) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 4}
0.729627 (0.024273) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 8}
0.752945 (0.018158) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 16}
0.756791 (0.019520) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 32}
0.343570 (0.039231) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 1}
0.532813 (0.033247) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 2}
0.660397 (0.031042) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 4}
0.714303 (0.012821) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 8}
0.749099 (0.026874) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 16}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 32}
0.304868 (0.040223) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 1}
0.498077 (0.022673) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 2}
0.602344 (0.029067) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 4}
0.679627 (0.028552) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 8}
0.745373 (0.040419) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 16}
0.760757 (0.026664) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 32}
0.447837 (0.167344) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 1}
0.668269 (0.108866) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 2}
0.726022 (0.050735) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 4}
0.749099 (0.028992) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 8}
0.764603 (0.028645) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 16}
0.760757 (0.026664) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 32}
0.440024 (0.168371) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 1}
0.656731 (0.121546) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 2}
0.710577 (0.054077) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 4}
0.737560 (0.036974) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 8}
0.749099 (0.026874) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 16}
0.749099 (0.015774) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 2, 'n_estimators': 32}
0.416827 (0.144291) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 1}
0.606370 (0.109513) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 2}
0.706731 (0.059855) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 4}
0.737560 (0.036974) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 8}
0.737440 (0.018925) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 16}
0.749099 (0.015774) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 3, 'n_estimators': 32}
0.355288 (0.089329) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 1}
0.556130 (0.074038) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 2}
0.683654 (0.062869) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 4}
0.721995 (0.011039) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 8}
0.733594 (0.033238) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 16}
0.760757 (0.026664) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'n_estimators': 32}
0.320312 (0.040164) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 1}
0.474880 (0.011440) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 2}
0.614062 (0.053308) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 4}
0.656490 (0.070256) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 8}
0.733594 (0.033238) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 16}
0.749099 (0.019162) with: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 5, 'n_estimators': 32}
0.764363 (0.041944) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 1}
0.776202 (0.030855) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 2}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 4}
0.764663 (0.032232) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 8}
0.764603 (0.028645) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 16}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'n_estimators': 32}
0.675240 (0.100375) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 1}
0.752885 (0.018916) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 2}
0.753005 (0.020584) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 4}
0.760697 (0.024783) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 8}
0.764603 (0.028645) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 16}
0.760697 (0.022267) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'n_estimators': 32}
0.547536 (0.109898) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 1}
0.656070 (0.050378) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 2}
0.725901 (0.022300) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 4}
0.737440 (0.018925) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 8}
0.745192 (0.025276) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 16}
0.760697 (0.022267) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 3, 'n_estimators': 32}
0.378365 (0.038254) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 1}
0.582993 (0.039324) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 2}
0.683474 (0.021994) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 4}
0.718269 (0.026280) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 8}
0.745252 (0.022212) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 16}
0.753065 (0.031541) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 32}
0.281791 (0.028924) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 1}
0.501863 (0.030502) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 2}
0.610276 (0.049877) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 4}
0.671875 (0.018908) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 8}
0.737380 (0.016537) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 16}
0.756791 (0.019520) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'n_estimators': 32}
0.764363 (0.041944) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 1}
0.776202 (0.030855) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 2}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 4}
0.764663 (0.032232) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 8}
0.764603 (0.028645) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 16}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'n_estimators': 32}
0.698738 (0.062523) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 1}
0.772356 (0.028519) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 2}
0.756911 (0.026271) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 4}
0.760757 (0.026664) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 8}
0.764603 (0.028645) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 16}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 32}
0.574940 (0.079522) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 1}
0.698798 (0.033869) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 2}
0.737500 (0.014487) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 4}
0.760757 (0.030784) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 8}
0.760697 (0.024783) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 16}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 3, 'n_estimators': 32}
0.366406 (0.075061) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 1}
0.613702 (0.044034) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 2}
0.710637 (0.036918) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 4}
0.737500 (0.014487) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 8}
0.756911 (0.034111) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 16}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 4, 'n_estimators': 32}
0.281911 (0.023410) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 1}
0.502163 (0.042950) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 2}
0.621695 (0.040717) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 4}
0.683534 (0.032320) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 8}
0.749219 (0.052994) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 16}
0.764603 (0.026499) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 5, 'n_estimators': 32}
0.764363 (0.041944) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 1}
0.776202 (0.030855) with: {'criterion': 'gini', 'max_depth': 10, 'max_features': None, 'min_samples_leaf': 1, 'n_estimators': 2}

In [32]:
# Random Forest
random_forest = RandomForestClassifier(criterion='gini', max_depth=10, max_features='sqrt', min_samples_leaf= 1, n_estimators=2, n_jobs=4, random_state=1)
random_forest_cv_results = cross_val_score(random_forest, X_train, y_train, cv=4, verbose=3)

[CV] END ................................ score: (test=0.800) total time=   0.0s
[CV] END ................................ score: (test=0.738) total time=   0.0s
[CV] END ................................ score: (test=0.754) total time=   0.0s
[CV] END ................................ score: (test=0.812) total time=   0.0s

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

In [33]:
print("accuracy: {}, std: {}".format(random_forest_cv_results.mean(), random_forest_cv_results.std()))

accuracy: 0.776201923076923, std: 0.030854561665849607

## Neural Network

In [34]:
# size of hidden layer
hidden_layer_sizes = [(9,), (10,), (11,), (12,), (13,), (14,), (15,), (40,)]
# hidden layer activation function
activation = ['identity', 'logistic', 'tanh', 'relu']
# solver
solver = ['lbfgs']
# L2 regularization term strength
alpha = [0.0001, 0.001, 0.01, 0.1, 1]
# create the params grid
param_grid = {'hidden_layer_sizes': hidden_layer_sizes,
              'activation': activation,
              'solver': solver,
              'alpha': alpha}

In [35]:
# GridSearchCV fit
model = MLPClassifier(random_state=1)

grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring="accuracy", cv=4, verbose=3)
grid_result = grid.fit(X_train.values, y_train.values)

Fitting 4 folds for each of 160 candidates, totalling 640 fits

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.797 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.797 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.797 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.797 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.797 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.4s
[CV 1/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.797 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.797 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=identity, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=identity, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=identity, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=identity, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.692 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.688 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.692 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.708 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.734 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.692 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.692 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.734 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.692 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.692 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.692 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=logistic, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=logistic, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=logistic, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=logistic, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.708 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.672 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.631 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.750 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.738 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.692 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.734 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.738 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.734 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.692 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.750 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.692 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.766 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.719 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.738 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s
[CV 2/4] END activation=tanh, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s
[CV 3/4] END activation=tanh, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=tanh, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=tanh, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=tanh, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=tanh, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.5s
[CV 1/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.015 total time=   0.0s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.215 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.200 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.406 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.292 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.246 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.231 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.328 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.677 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.3s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.415 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.734 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.662 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.292 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.585 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.438 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.3s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.508 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.797 total time=   0.3s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.646 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.600 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.3s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.508 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.308 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.215 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.219 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.0001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.4s
[CV 1/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.015 total time=   0.0s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.215 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.200 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.453 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.292 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.308 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.215 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.328 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.662 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.431 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.734 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.631 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.277 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.631 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.438 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.600 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.738 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.569 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.385 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.508 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.338 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.215 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.219 total time=   0.3s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.001, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.797 total time=   0.4s
[CV 1/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.015 total time=   0.0s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.215 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.200 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.516 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.262 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.246 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.246 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.266 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.662 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.585 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.631 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.169 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.631 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.438 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.646 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.738 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.631 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.569 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.200 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.215 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.750 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.01, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.2s
[CV 2/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.719 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.785 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.692 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=0.1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=1, hidden_layer_sizes=(9,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.769 total time=   0.1s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=1, hidden_layer_sizes=(10,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=1, hidden_layer_sizes=(11,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=1, hidden_layer_sizes=(12,), solver=lbfgs;, score=0.797 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=1, hidden_layer_sizes=(13,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=1, hidden_layer_sizes=(14,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.769 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.723 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.754 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=1, hidden_layer_sizes=(15,), solver=lbfgs;, score=0.766 total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 1/4] END activation=relu, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.769 total time=   0.5s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 2/4] END activation=relu, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.723 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 3/4] END activation=relu, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.754 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV 4/4] END activation=relu, alpha=1, hidden_layer_sizes=(40,), solver=lbfgs;, score=0.766 total time=   0.4s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

In [36]:
# GridSearchCV result
print("Best: {} using {}".format(round(grid_result.best_score_, 6), grid_result.best_params_)) 

means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']

for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.764603 using {'activation': 'relu', 'alpha': 0.1, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.0001, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.0001, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.0001, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.0001, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.0001, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.0001, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.0001, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.0001, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.01, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.01, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.01, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.01, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.01, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.01, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.01, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.01, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.1, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.1, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.1, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.1, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.1, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'identity', 'alpha': 0.1, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.1, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 0.1, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 1, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 1, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 1, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 1, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 1, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 1, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 1, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'identity', 'alpha': 1, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.745252 (0.031093) with: {'activation': 'logistic', 'alpha': 0.0001, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.721875 (0.023488) with: {'activation': 'logistic', 'alpha': 0.0001, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.733714 (0.028510) with: {'activation': 'logistic', 'alpha': 0.0001, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.741286 (0.022994) with: {'activation': 'logistic', 'alpha': 0.0001, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'logistic', 'alpha': 0.0001, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.0001, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'logistic', 'alpha': 0.0001, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.0001, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.001, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.001, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.001, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.001, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'logistic', 'alpha': 0.001, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.001, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.001, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.001, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'logistic', 'alpha': 0.01, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.01, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.01, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.01, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'logistic', 'alpha': 0.01, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.01, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.01, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.01, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.1, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.1, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.1, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.1, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.1, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.1, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.1, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 0.1, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.745252 (0.031093) with: {'activation': 'logistic', 'alpha': 1, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.737440 (0.028836) with: {'activation': 'logistic', 'alpha': 1, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.737560 (0.031813) with: {'activation': 'logistic', 'alpha': 1, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.737560 (0.031813) with: {'activation': 'logistic', 'alpha': 1, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.745252 (0.031093) with: {'activation': 'logistic', 'alpha': 1, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 1, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 1, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'logistic', 'alpha': 1, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.714123 (0.029514) with: {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.722115 (0.052762) with: {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.745373 (0.037376) with: {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.745132 (0.017740) with: {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.737440 (0.011022) with: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.737500 (0.026139) with: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.753065 (0.038317) with: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.01, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.741226 (0.021084) with: {'activation': 'tanh', 'alpha': 0.01, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'tanh', 'alpha': 0.01, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'tanh', 'alpha': 0.01, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.01, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.01, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'tanh', 'alpha': 0.01, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.01, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.1, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.756791 (0.012015) with: {'activation': 'tanh', 'alpha': 0.1, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.1, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.1, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.1, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.1, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.1, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 0.1, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.749099 (0.015774) with: {'activation': 'tanh', 'alpha': 1, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.749099 (0.015774) with: {'activation': 'tanh', 'alpha': 1, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 1, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'tanh', 'alpha': 1, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 1, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 1, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 1, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'tanh', 'alpha': 1, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.209255 (0.138308) with: {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.274339 (0.038433) with: {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.637440 (0.129998) with: {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.493990 (0.141556) with: {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.699219 (0.113677) with: {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.691406 (0.070374) with: {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.312380 (0.118684) with: {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.220974 (0.155429) with: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.285877 (0.042636) with: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.637440 (0.122499) with: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.493990 (0.148093) with: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.722296 (0.075369) with: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.614483 (0.152563) with: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.320072 (0.119127) with: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.236599 (0.179291) with: {'activation': 'relu', 'alpha': 0.01, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.254868 (0.008833) with: {'activation': 'relu', 'alpha': 0.01, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.691526 (0.078139) with: {'activation': 'relu', 'alpha': 0.01, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.467067 (0.189194) with: {'activation': 'relu', 'alpha': 0.01, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.726022 (0.049556) with: {'activation': 'relu', 'alpha': 0.01, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.729988 (0.061154) with: {'activation': 'relu', 'alpha': 0.01, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.433654 (0.234889) with: {'activation': 'relu', 'alpha': 0.01, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 0.01, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'relu', 'alpha': 0.1, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.741226 (0.021084) with: {'activation': 'relu', 'alpha': 0.1, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 0.1, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 0.1, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.764603 (0.028645) with: {'activation': 'relu', 'alpha': 0.1, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'relu', 'alpha': 0.1, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.733714 (0.028510) with: {'activation': 'relu', 'alpha': 0.1, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 0.1, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 1, 'hidden_layer_sizes': (9,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 1, 'hidden_layer_sizes': (10,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 1, 'hidden_layer_sizes': (11,), 'solver': 'lbfgs'}
0.760757 (0.026664) with: {'activation': 'relu', 'alpha': 1, 'hidden_layer_sizes': (12,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 1, 'hidden_layer_sizes': (13,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 1, 'hidden_layer_sizes': (14,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 1, 'hidden_layer_sizes': (15,), 'solver': 'lbfgs'}
0.752945 (0.018158) with: {'activation': 'relu', 'alpha': 1, 'hidden_layer_sizes': (40,), 'solver': 'lbfgs'}

In [37]:
# neural network
neural_network = MLPClassifier(activation='relu', alpha=0.1, hidden_layer_sizes=(13,), solver='lbfgs', random_state=1)
neural_network_cv_results = cross_val_score(neural_network, X_train, y_train, cv=4, verbose=3)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s

[CV] END ................................ score: (test=0.785) total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.5s remaining:    0.0s

[CV] END ................................ score: (test=0.723) total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

[CV] END ................................ score: (test=0.754) total time=   0.2s
[CV] END ................................ score: (test=0.797) total time=   0.2s

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    1.1s finished

In [38]:
print("accuracy: {}, std: {}".format(neural_network_cv_results.mean(), neural_network_cv_results.std()))

accuracy: 0.7646033653846154, std: 0.028644817704337362

In [39]:
# print each model accuracy (std)
print("svm(svc): {} ({})".format(svm_cv_results.mean(), svm_cv_results.std()))
print("random forest: {} ({})".format(random_forest_cv_results.mean(), random_forest_cv_results.std()))
print("neural network: {} ({})".format(neural_network_cv_results.mean(), neural_network_cv_results.std()))

svm(svc): 0.7529447115384615 (0.018158488211042722)
random forest: 0.776201923076923 (0.030854561665849607)
neural network: 0.7646033653846154 (0.028644817704337362)

# Create Model

In [40]:
# fit final model
final_model = RandomForestClassifier(criterion='gini', max_depth=10, max_features='sqrt', min_samples_leaf= 1, n_estimators=2, n_jobs=4, random_state=1)
final_model.fit(X_train.values, y_train.values)

y_pred = final_model.predict(X_test.values)

In [41]:
# train test accuracy score
print("train accuracy: {}, test accuracy: {}".format(round(final_model.score(X_train.values, y_train.values), 3), round(final_model.score(X_test.values, y_test.values), 3)))

train accuracy: 0.78, test accuracy: 0.793

In [42]:
# classification report
print(classification_report(y_test.values, y_pred, digits=3))

              precision    recall  f1-score   support

           0      1.000     1.000     1.000         3
           1      0.000     0.000     0.000         3
           2      1.000     1.000     1.000         3
           3      1.000     1.000     1.000         3
           4      1.000     1.000     1.000         3
           5      0.000     0.000     0.000         3
           6      0.000     0.000     0.000         3
           7      1.000     0.333     0.500         3
           8      1.000     1.000     1.000         3
           9      0.333     1.000     0.500         3
          10      1.000     1.000     1.000         3
          11      0.333     1.000     0.500         3
          12      0.000     0.000     0.000         3
          13      1.000     1.000     1.000         3
          14      1.000     1.000     1.000         3
          15      0.000     0.000     0.000         3
          16      1.000     1.000     1.000         3
          17      1.000     1.000     1.000         3
          18      1.000     1.000     1.000         3
          19      1.000     1.000     1.000         3
          20      1.000     1.000     1.000         3
          21      1.000     1.000     1.000         3
          22      1.000     1.000     1.000         3
          23      0.000     0.000     0.000         3
          24      1.000     1.000     1.000         3
          25      1.000     1.000     1.000         3
          26      1.000     1.000     1.000         3
          27      1.000     1.000     1.000         3
          28      0.273     1.000     0.429         3
          29      1.000     1.000     1.000         3
          30      0.500     1.000     0.667         3
          31      0.000     0.000     0.000         3
          32      1.000     1.000     1.000         3
          33      1.000     1.000     1.000         3
          34      1.000     1.000     1.000         3
          35      1.000     1.000     1.000         3
          36      1.000     1.000     1.000         3

    accuracy                          0.793       111
   macro avg      0.742     0.793     0.746       111
weighted avg      0.742     0.793     0.746       111

C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\marce\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [43]:
# top 5 accuracy
y_pred_probs = final_model.predict_proba(X_test.values)
print('top 5 accuracy: %s' % top_k_accuracy_score(y_test.values, y_pred_probs, k=5))

top 5 accuracy: 1.0

# Prediction Testing

final_model.predict testing

In [44]:
final_prediction = final_model.predict([[6,1,1,1,0,0,1,0]])
final_prediction

array([28])

In [45]:
# inverse transform predicted class
print(lbl_encoder.inverse_transform(final_prediction)[0])

Discoaster pseudovariabilis

final_model.predict_proba testing

In [46]:
probs = final_model.predict_proba([[6,1,1,1,0,0,1,0]])
probs

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.07255747, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.28017241, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.37715517, 0.        ,
        0.        , 0.27011494, 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [47]:
# sort prediction probabilitises
sorted_probs = sorted(probs[0], reverse=True)
sorted_probs

[0.3771551724137931,
 0.2801724137931034,
 0.27011494252873564,
 0.07255747126436782,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [48]:
# search top five prediction probabilities
top_five_probs = [sorted_probs[0], sorted_probs[1], sorted_probs[2], sorted_probs[3], sorted_probs[4]]
top_five_probs

[0.3771551724137931,
 0.2801724137931034,
 0.27011494252873564,
 0.07255747126436782,
 0.0]

In [49]:
# search best five prediction class
best_n = np.argsort(probs)[:,-5:]
best_n[0]

array([ 8,  7, 31, 15, 28], dtype=int64)

In [50]:
# rank best five prediction class from the best
best_five_species = [best_n[0][4], best_n[0][3], best_n[0][2], best_n[0][1], best_n[0][0]]
best_five_species

[28, 15, 31, 7, 8]

In [51]:
# inverse transform ranked best five predicted class
lbl_encoder.inverse_transform(best_five_species)

array(['Discoaster pseudovariabilis', 'Discoaster exilis',
       'Discoaster subsurculus', 'Discoaster bollii',
       'Discoaster braarudii'], dtype=object)

# Saving Models

In [52]:
# save trained random forest model
save_model(final_model, "random_forest_nannomate.pkl")

Model is pickled as model/random_forest_nannomate.pkl

In [53]:
# save label encoder
save_model(lbl_encoder, "lbl_encoder_nannomate.pkl")

Model is pickled as model/lbl_encoder_nannomate.pkl

In [54]:
# save ordinal encoder
save_model(ordl_encoder, "ordl_encoder_nannomate.pkl")

Model is pickled as model/ordl_encoder_nannomate.pkl